// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title Groth16 Verifier — BN254 pairing-based proof verification
/// @author Ontic Labs
/// @notice Standard Groth16 verifier with VK from deterministic trusted setup
/// @dev VK generated by `cargo run --bin generate-vk --features groth16`
///      Circuit: SimpleMembershipCircuit (secret² = hash), 1 public input
///      Curve: BN254 (alt_bn128), ecPairing precompile 0x08
///      Deterministic seed: 0x4859_5045_5254_454E ("HYPERTEN" in ASCII)
contract Groth16Verifier {

    // ═══════════════════════════════════════════════════════════════════════
    // BN254 FIELD MODULI
    // ═══════════════════════════════════════════════════════════════════════

    /// @notice Base field modulus (Fq)
    uint256 internal constant P = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @notice Scalar field modulus (Fr)
    uint256 internal constant Q = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // ═══════════════════════════════════════════════════════════════════════
    // VERIFICATION KEY — deterministic trusted setup
    // ═══════════════════════════════════════════════════════════════════════

    // α ∈ G1
    uint256 internal constant ALPHA_X = 0x0af2c4ad40c3bf1a234612c4bc3ceb7e7b8efc6c43b25278accf3fc8d4f47bfc;
    uint256 internal constant ALPHA_Y = 0x13a20c78bbc2497cd44e0ab6fc2bf573d269070c6e9ca7b1380aa9dfa7934cd5;

    // β ∈ G2 (X1 = x.c1 = imaginary, X2 = x.c0 = real)
    uint256 internal constant BETA_X1 = 0x103cdf3c987b1c7e28a6feab73b300a6c85a01b36ddfe88f8b133b7c5c797aaa;
    uint256 internal constant BETA_X2 = 0x305af8adbb29f56a3ce1509ea9442e239cc5501beb7e2aa84c8cf45f2b61fa5c;
    uint256 internal constant BETA_Y1 = 0x2ebd317e792ab593028ebf61e14aea0d1f150770c2c0f05384763e1f069534ba;
    uint256 internal constant BETA_Y2 = 0x16ca8b4078f94197504352b9fb577fcee74cd2ecfd5801c19660cbe64bb8947e;

    // γ ∈ G2
    uint256 internal constant GAMMA_X1 = 0x2b3f62cec751449eeec1597cf4aebfce711a1a1265bc4d8e1e7ad8dc37eddf4a;
    uint256 internal constant GAMMA_X2 = 0x0b750f175138e42380c97bcbe292fa7f752e6b7c69cc82b740a749b38a0ad79e;
    uint256 internal constant GAMMA_Y1 = 0x088f92774e16c66ad47f939b07ae0903139d5e6ef1668f10b1c9abde97281ef3;
    uint256 internal constant GAMMA_Y2 = 0x1075d3cf9b06f5a49871cb3cba3affcfcc651470e085aeb9412696292de8f0e2;

    // δ ∈ G2
    uint256 internal constant DELTA_X1 = 0x1ac0085d58dd301e360fce5356eb402ea77bcd36f0672e51579b41633c7aa4ca;
    uint256 internal constant DELTA_X2 = 0x1a55045d9fbe8120538e8c289538832c0927e3d0e211b0ff43bc1aa7dd63cd86;
    uint256 internal constant DELTA_Y1 = 0x27952cdd0d489db9a891f882906370f34fe877a3817ff05457e054e344f92ebe;
    uint256 internal constant DELTA_Y2 = 0x0ac8a933f145ecce425589a700769ada27baea0e38ad35eb2dab54afa90e2fa2;

    // IC[0] = constant term, IC[1] = coefficient for public input (hash)
    uint256 internal constant IC0_X = 0x02a4e05bed12976cacfe168fc5d52d35607f498874a2b65a72654ef12065137e;
    uint256 internal constant IC0_Y = 0x24c9d34c37cdc8b92101ce6676be7b2719fc1614385378564e5e1f9ec4efe07a;

    uint256 internal constant IC1_X = 0x0358dbe66ac4d13366ae8d91b9bc67e4020e11b21c61d14062a3e4235eabced0;
    uint256 internal constant IC1_Y = 0x05fbf9cca81492825a6316792161ba4e35591f188a7e39fcce1a292054c1441a;

    // ═══════════════════════════════════════════════════════════════════════
    // ERRORS
    // ═══════════════════════════════════════════════════════════════════════

    error InvalidProof();
    error InvalidPublicInput();
    error PairingFailed();

    // ═══════════════════════════════════════════════════════════════════════
    // VERIFICATION
    // ═══════════════════════════════════════════════════════════════════════

    /// @notice Verify a Groth16 proof with 1 public input
    /// @param proof [A.x, A.y, B.x1, B.x0, B.y1, B.y0, C.x, C.y]
    /// @param publicInput Single public field element (hash = secret²)
    /// @return True if proof is valid
    function verifyProof(
        uint256[8] calldata proof,
        uint256 publicInput
    ) external view returns (bool) {
        // Validate public input is in scalar field
        if (publicInput >= Q) revert InvalidPublicInput();

        // Compute vk_x = IC[0] + publicInput · IC[1]
        uint256 vkX = IC0_X;
        uint256 vkY = IC0_Y;

        (uint256 mulX, uint256 mulY) = _ecMul(IC1_X, IC1_Y, publicInput);
        (vkX, vkY) = _ecAdd(vkX, vkY, mulX, mulY);

        // Standard Groth16 pairing check:
        // e(-A, B) · e(α, β) · e(vk_x, γ) · e(C, δ) = 1
        return _verifyPairing(
            proof[0], proof[1],
            proof[2], proof[3], proof[4], proof[5],
            proof[6], proof[7],
            vkX, vkY
        );
    }

    // ═══════════════════════════════════════════════════════════════════════
    // BN254 PRECOMPILE WRAPPERS
    // ═══════════════════════════════════════════════════════════════════════

    /// @notice EC scalar multiplication via precompile 0x07
    function _ecMul(uint256 px, uint256 py, uint256 s) internal view returns (uint256, uint256) {
        uint256[3] memory input;
        input[0] = px;
        input[1] = py;
        input[2] = s;

        uint256[2] memory result;
        bool success;

        assembly {
            success := staticcall(sub(gas(), 2000), 0x07, input, 96, result, 64)
        }

        require(success, "ecMul failed");
        return (result[0], result[1]);
    }

    /// @notice EC point addition via precompile 0x06
    function _ecAdd(uint256 p1x, uint256 p1y, uint256 p2x, uint256 p2y) internal view returns (uint256, uint256) {
        uint256[4] memory input;
        input[0] = p1x;
        input[1] = p1y;
        input[2] = p2x;
        input[3] = p2y;

        uint256[2] memory result;
        bool success;

        assembly {
            success := staticcall(sub(gas(), 2000), 0x06, input, 128, result, 64)
        }

        require(success, "ecAdd failed");
        return (result[0], result[1]);
    }

    /// @notice Verify Groth16 pairing via ecPairing precompile 0x08
    /// @dev Checks e(-A, B) · e(α, β) · e(vk_x, γ) · e(C, δ) = 1
    function _verifyPairing(
        uint256 aX, uint256 aY,
        uint256 bX1, uint256 bX0,
        uint256 bY1, uint256 bY0,
        uint256 cX, uint256 cY,
        uint256 vkX, uint256 vkY
    ) internal view returns (bool) {
        uint256[24] memory input;

        // Pairing 1: e(-A, B)
        input[0] = aX;
        input[1] = P - aY; // negate A
        // EIP-197: G2 encoding is (x_imaginary, x_real, y_imaginary, y_real)
        input[2] = bX1;    // x.c1 (imaginary)
        input[3] = bX0;    // x.c0 (real)
        input[4] = bY1;    // y.c1 (imaginary)
        input[5] = bY0;    // y.c0 (real)

        // Pairing 2: e(α, β)
        input[6] = ALPHA_X;
        input[7] = ALPHA_Y;
        input[8] = BETA_X1;
        input[9] = BETA_X2;
        input[10] = BETA_Y1;
        input[11] = BETA_Y2;

        // Pairing 3: e(vk_x, γ)
        input[12] = vkX;
        input[13] = vkY;
        input[14] = GAMMA_X1;
        input[15] = GAMMA_X2;
        input[16] = GAMMA_Y1;
        input[17] = GAMMA_Y2;

        // Pairing 4: e(C, δ)
        input[18] = cX;
        input[19] = cY;
        input[20] = DELTA_X1;
        input[21] = DELTA_X2;
        input[22] = DELTA_Y1;
        input[23] = DELTA_Y2;

        uint256[1] memory result;
        bool success;

        assembly {
            success := staticcall(sub(gas(), 2000), 0x08, input, 768, result, 32)
        }

        // Return false on precompile failure (off-curve points, invalid input)
        // or when the pairing equation is not satisfied (result[0] != 1).
        return success && result[0] == 1;
    }
}
