# Funding and sponsorship links for The Ontic Engine
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom:
  - "https://tigantic.com/invest"
