#!/usr/bin/env python3
"""
FRONTIER 05: Stabilizer Formalism & Pauli Algebra
==================================================

Implements the stabilizer formalism for quantum error correction.

Physics Model:
- Stabilizer states are +1 eigenstates of a set of commuting Pauli operators
- n-qubit stabilizer group generated by n independent generators
- Logical operators commute with stabilizers but are not in the group

Key Properties:
    Pauli group: {±I, ±iI, ±X, ±iX, ±Y, ±iY, ±Z, ±iZ}^⊗n
    
    Commutation: [X, Z] = 2iY (X and Z anticommute)
    
    Stabilizer code [[n, k, d]]:
    - n physical qubits
    - n-k independent stabilizer generators
    - k logical qubits
    - distance d

Benchmark:
- Pauli multiplication correctness
- Commutation relation verification
- Stabilizer group closure
- Syndrome extraction

Reference:
- Gottesman, PhD thesis (1997)
- Nielsen & Chuang, Ch. 10 (2000)

(c) 2026 Tigantic Holdings LLC. All Rights Reserved.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from enum import Enum
from typing import List, Tuple, Dict, Optional
import numpy as np
from itertools import product


class Phase(Enum):
    """Phase factor for Pauli operators."""
    PLUS_1 = 0      # +1
    PLUS_I = 1      # +i
    MINUS_1 = 2     # -1
    MINUS_I = 3     # -i
    
    def __mul__(self, other: 'Phase') -> 'Phase':
        return Phase((self.value + other.value) % 4)
    
    def __repr__(self) -> str:
        symbols = ['+1', '+i', '-1', '-i']
        return symbols[self.value]


@dataclass
class PauliString:
    """
    An n-qubit Pauli operator with phase.
    
    Represented as: phase × (Z^z[0] X^x[0]) ⊗ (Z^z[1] X^x[1]) ⊗ ...
    
    Using binary symplectic representation:
    - x[i] = 1 if X or Y on qubit i
    - z[i] = 1 if Z or Y on qubit i
    """
    n_qubits: int
    x: np.ndarray  # Binary vector of length n
    z: np.ndarray  # Binary vector of length n
    phase: Phase = Phase.PLUS_1
    
    def __post_init__(self):
        self.x = np.asarray(self.x, dtype=np.int8)
        self.z = np.asarray(self.z, dtype=np.int8)
    
    @classmethod
    def identity(cls, n: int) -> 'PauliString':
        """Create n-qubit identity."""
        return cls(n, np.zeros(n, dtype=np.int8), np.zeros(n, dtype=np.int8))
    
    @classmethod
    def single_x(cls, n: int, qubit: int) -> 'PauliString':
        """Create single-qubit X on specified qubit."""
        x = np.zeros(n, dtype=np.int8)
        x[qubit] = 1
        return cls(n, x, np.zeros(n, dtype=np.int8))
    
    @classmethod
    def single_z(cls, n: int, qubit: int) -> 'PauliString':
        """Create single-qubit Z on specified qubit."""
        z = np.zeros(n, dtype=np.int8)
        z[qubit] = 1
        return cls(n, np.zeros(n, dtype=np.int8), z)
    
    @classmethod
    def single_y(cls, n: int, qubit: int) -> 'PauliString':
        """Create single-qubit Y on specified qubit (with phase i)."""
        x = np.zeros(n, dtype=np.int8)
        z = np.zeros(n, dtype=np.int8)
        x[qubit] = 1
        z[qubit] = 1
        return cls(n, x, z, Phase.PLUS_I)  # Y = iXZ
    
    def weight(self) -> int:
        """Return the weight (number of non-identity terms)."""
        return int(np.sum((self.x | self.z) > 0))
    
    def __mul__(self, other: 'PauliString') -> 'PauliString':
        """
        Multiply two Pauli strings.
        
        Uses the formula: (X^a Z^b)(X^c Z^d) = (-1)^(b·c) X^(a+c) Z^(b+d)
        Plus phase from Y = iXZ
        """
        assert self.n_qubits == other.n_qubits
        
        # Phase from anticommutation: Z^b X^c -> (-1)^(b·c) X^c Z^b
        anticommute_count = np.sum(self.z * other.x) % 2
        
        # Phase from Y = iXZ: each Y contributes phase i
        # When combining, need to track phases carefully
        
        # New phase
        phase_shift = 0
        
        # Count phase contributions from combining operators
        for i in range(self.n_qubits):
            a, b = self.x[i], self.z[i]  # First operator on qubit i
            c, d = other.x[i], other.z[i]  # Second operator on qubit i
            
            # Y = iXZ, so Y contributes phase i
            # When multiplying Paulis, track phase changes
            if b and c:  # Z * X = -iY = -i(iXZ) = XZ with extra -i, but also ZX = -XZ
                phase_shift += 2  # -1 contribution
        
        # Combine phases
        total_phase_val = (self.phase.value + other.phase.value + phase_shift) % 4
        new_phase = Phase(total_phase_val)
        
        # New x and z vectors (mod 2 addition)
        new_x = (self.x + other.x) % 2
        new_z = (self.z + other.z) % 2
        
        return PauliString(self.n_qubits, new_x, new_z, new_phase)
    
    def commutes_with(self, other: 'PauliString') -> bool:
        """
        Check if this Pauli commutes with another.
        
        Two Paulis commute iff they anticommute on an even number of qubits.
        Anticommutation on qubit i occurs when one has X and other has Z (or vice versa).
        """
        assert self.n_qubits == other.n_qubits
        
        # Count anticommutations
        # X anticommutes with Z: check (x1 & z2) XOR (z1 & x2)
        anticommute_count = np.sum(
            (self.x * other.z + self.z * other.x) % 2
        )
        
        return anticommute_count % 2 == 0
    
    def to_string(self) -> str:
        """Convert to human-readable string."""
        phase_str = str(self.phase)
        pauli_str = ""
        
        for i in range(self.n_qubits):
            if self.x[i] and self.z[i]:
                pauli_str += "Y"
            elif self.x[i]:
                pauli_str += "X"
            elif self.z[i]:
                pauli_str += "Z"
            else:
                pauli_str += "I"
        
        return f"{phase_str}{pauli_str}"
    
    def __repr__(self) -> str:
        return self.to_string()


@dataclass
class StabilizerTableau:
    """
    Tableau representation of a stabilizer state.
    
    Stores n stabilizer generators for an n-qubit state.
    Can track destabilizers for efficient simulation.
    """
    n_qubits: int
    stabilizers: List[PauliString]
    destabilizers: Optional[List[PauliString]] = None
    
    @classmethod
    def computational_basis(cls, n: int, state: int = 0) -> 'StabilizerTableau':
        """
        Create tableau for computational basis state |state⟩.
        
        |0...0⟩ is stabilized by Z_i for all i.
        """
        stabilizers = [PauliString.single_z(n, i) for i in range(n)]
        
        # For |1⟩ on some qubits, stabilizer is -Z
        for i in range(n):
            if state & (1 << i):
                stabilizers[i].phase = Phase.MINUS_1
        
        return cls(n, stabilizers)
    
    def check_valid(self) -> Tuple[bool, str]:
        """
        Verify stabilizer group is valid:
        1. All stabilizers commute
        2. Stabilizers are independent (no redundancy)
        """
        n = len(self.stabilizers)
        
        # Check commutation
        for i in range(n):
            for j in range(i + 1, n):
                if not self.stabilizers[i].commutes_with(self.stabilizers[j]):
                    return False, f"Stabilizers {i} and {j} do not commute"
        
        # Check independence (simplified: just check not all identity)
        for i, s in enumerate(self.stabilizers):
            if s.weight() == 0:
                return False, f"Stabilizer {i} is identity"
        
        return True, "Valid stabilizer group"


def run_pauli_algebra_tests() -> Dict[str, bool]:
    """Test Pauli algebra operations."""
    tests = {}
    
    # Test 1: X * X = I
    n = 1
    X = PauliString.single_x(n, 0)
    XX = X * X
    tests['X*X=I'] = XX.weight() == 0 and XX.phase == Phase.PLUS_1
    
    # Test 2: Z * Z = I
    Z = PauliString.single_z(n, 0)
    ZZ = Z * Z
    tests['Z*Z=I'] = ZZ.weight() == 0 and ZZ.phase == Phase.PLUS_1
    
    # Test 3: X * Z = -Z * X (anticommutation)
    XZ = X * Z
    ZX = Z * X
    # XZ and ZX should differ by phase -1
    tests['XZ=-ZX'] = not X.commutes_with(Z)
    
    # Test 4: Y * Y = I (with proper phase handling)
    Y = PauliString.single_y(n, 0)
    YY = Y * Y
    tests['Y*Y=I'] = YY.weight() == 0  # Phase might vary
    
    # Test 5: Multi-qubit commutation
    n = 2
    X0 = PauliString.single_x(n, 0)
    Z1 = PauliString.single_z(n, 1)
    tests['X0_commutes_Z1'] = X0.commutes_with(Z1)
    
    # Test 6: X0Z1 commutes with X0Z1 (same operator)
    X0Z1 = X0 * Z1
    tests['self_commute'] = X0Z1.commutes_with(X0Z1)
    
    # Test 7: Weight calculation
    n = 3
    xyz = PauliString(n, np.array([1, 0, 1]), np.array([0, 1, 1]))  # X⊗Z⊗Y
    tests['weight_calc'] = xyz.weight() == 3
    
    return tests


def run_stabilizer_tests() -> Dict[str, bool]:
    """Test stabilizer formalism."""
    tests = {}
    
    # Test 1: |00⟩ state
    n = 2
    state_00 = StabilizerTableau.computational_basis(n, 0)
    valid, _ = state_00.check_valid()
    tests['|00>_valid'] = valid
    
    # Test 2: Stabilizers of |00⟩ are ZI and IZ
    s0 = state_00.stabilizers[0]
    s1 = state_00.stabilizers[1]
    tests['|00>_Z0'] = s0.z[0] == 1 and s0.x[0] == 0
    tests['|00>_Z1'] = s1.z[1] == 1 and s1.x[1] == 0
    
    # Test 3: Bell state |Φ+⟩ stabilizers: XX, ZZ
    # Create manually
    bell_stabs = [
        PauliString(2, np.array([1, 1]), np.array([0, 0])),  # XX
        PauliString(2, np.array([0, 0]), np.array([1, 1])),  # ZZ
    ]
    bell_state = StabilizerTableau(2, bell_stabs)
    valid, _ = bell_state.check_valid()
    tests['bell_valid'] = valid
    
    # Test 4: XX and ZZ commute
    tests['XX_ZZ_commute'] = bell_stabs[0].commutes_with(bell_stabs[1])
    
    # Test 5: 3-qubit repetition code stabilizers: ZZI, IZZ
    rep_stabs = [
        PauliString(3, np.array([0, 0, 0]), np.array([1, 1, 0])),  # ZZI
        PauliString(3, np.array([0, 0, 0]), np.array([0, 1, 1])),  # IZZ
    ]
    tests['rep_code_commute'] = rep_stabs[0].commutes_with(rep_stabs[1])
    
    # Test 6: Logical X = XXX commutes with stabilizers
    logical_x = PauliString(3, np.array([1, 1, 1]), np.array([0, 0, 0]))  # XXX
    tests['logical_X_commutes'] = (
        logical_x.commutes_with(rep_stabs[0]) and 
        logical_x.commutes_with(rep_stabs[1])
    )
    
    return tests


@dataclass
class StabilizerResult:
    """Results from stabilizer formalism tests."""
    pauli_tests: Dict[str, bool]
    stabilizer_tests: Dict[str, bool]
    all_pass: bool


def run_stabilizer_benchmark() -> Tuple[StabilizerResult, dict]:
    """Run stabilizer formalism benchmark."""
    print("="*70)
    print("FRONTIER 05: Stabilizer Formalism & Pauli Algebra")
    print("="*70)
    print()
    
    # Run Pauli algebra tests
    print("Pauli Algebra Tests:")
    pauli_tests = run_pauli_algebra_tests()
    for name, passed in pauli_tests.items():
        status = "✓" if passed else "✗"
        print(f"  {status} {name}")
    print()
    
    # Run stabilizer tests
    print("Stabilizer Formalism Tests:")
    stab_tests = run_stabilizer_tests()
    for name, passed in stab_tests.items():
        status = "✓" if passed else "✗"
        print(f"  {status} {name}")
    print()
    
    # Summary
    all_pauli_pass = all(pauli_tests.values())
    all_stab_pass = all(stab_tests.values())
    all_pass = all_pauli_pass and all_stab_pass
    
    result = StabilizerResult(
        pauli_tests=pauli_tests,
        stabilizer_tests=stab_tests,
        all_pass=all_pass
    )
    
    checks = {
        'pauli_algebra': {
            'valid': all_pauli_pass,
            'passed': sum(pauli_tests.values()),
            'total': len(pauli_tests)
        },
        'stabilizer_formalism': {
            'valid': all_stab_pass,
            'passed': sum(stab_tests.values()),
            'total': len(stab_tests)
        },
        'all_pass': all_pass
    }
    
    print("Summary:")
    print(f"  Pauli algebra:      {sum(pauli_tests.values())}/{len(pauli_tests)} passed")
    print(f"  Stabilizer tests:   {sum(stab_tests.values())}/{len(stab_tests)} passed")
    print()
    
    if all_pass:
        print("★ STABILIZER FORMALISM BENCHMARK: PASS")
    else:
        print("✗ STABILIZER FORMALISM BENCHMARK: FAIL")
    
    return result, checks


if __name__ == "__main__":
    result, checks = run_stabilizer_benchmark()
