{{- range $name, $pvc := dict "certificates" .Values.persistence.certificates "weights" .Values.persistence.weights "kzg-params" .Values.persistence.kzgParams }}
{{- if $pvc.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fluidelite.fullname" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "fluidelite.labels" $ | nindent 4 }}
spec:
  accessModes:
    - {{ $pvc.accessMode }}
  {{- if $pvc.storageClass }}
  storageClassName: {{ $pvc.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $pvc.size }}
{{- end }}
{{- end }}
