apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluidelite.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluidelite.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "fluidelite.selectorLabels" . | nindent 4 }}
