// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.21;

/// @title REAL Groth16 Verifier for Zero-Expansion
/// @notice Generated by arkworks - REAL cryptographic verification
contract Groth16VerifierReal {
    
    // BN254 curve constants
    uint256 internal constant P = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
    uint256 internal constant Q = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    
    // Verification Key (from trusted setup)
    uint256 internal constant ALPHA_X = 0x1d0f717d282bff68f12afa64732ec8dcf5028c0074187142a519cb7e4167a728;
    uint256 internal constant ALPHA_Y = 0x1edd9714fc371c2dfb53d11da63a77d9809d1849c58f8d585195bee0748d6ff4;
    
    uint256 internal constant BETA_X1 = 0x1f4b4fc602990b16fdef1e6f11faec43b747e35835ddacfac367efce8d817f4f;
    uint256 internal constant BETA_X2 = 0x2ebe85655a282510382c18df45093adfa22da79efb0d0f6c598850add26e3a55;
    uint256 internal constant BETA_Y1 = 0x02fe9bbd9b25d34d05ad3a975bca284c165c69e6bc4a20d040d115ecca2d970d;
    uint256 internal constant BETA_Y2 = 0x2bb3239bb79524afb9007af399394e7b8c2a34e7d3ac2829e0c5bc0edc0dce95;
    
    uint256 internal constant GAMMA_X1 = 0x1bb56282d3b7970dc05f4c347df23245645264e130b1494fab9c4cda146f7465;
    uint256 internal constant GAMMA_X2 = 0x1b4880b6ab03f2ffd95a050091ca1264b3465581b6f86b45695dd2b88cf879e4;
    uint256 internal constant GAMMA_Y1 = 0x085dcc4c489c5b878d78063ed428569eba84c51926f39ae2191acbe1a3394c55;
    uint256 internal constant GAMMA_Y2 = 0x12a80f7201a92eede33af748f0bae5c3d1afdca32231de199856a1d6ad2447b9;
    
    uint256 internal constant DELTA_X1 = 0x27cdc080f55428d0ab95d0289e02cab33f7cf2e6e59def37a03ec101ff1aaacb;
    uint256 internal constant DELTA_X2 = 0x004a4e69132030d832d6f2c092e651497943baccd5e304ef5341103ffc895aed;
    uint256 internal constant DELTA_Y1 = 0x2c4b09d5f5f5583e5f3ccb49862e4e7e01f7054a971a1d2c8cb9d65b063de523;
    uint256 internal constant DELTA_Y2 = 0x1fea5cad01a9e648f46a8540a22b01ad12d099814c8811a5cb923c8c99c50b2b;
    
    // IC points (for public input aggregation)
    uint256 internal constant IC0_X = 0x1e194bea53f62302afffffbd57fa841d8547b1d6ec63ffa4d92fb5b5ae7e1b35;
    uint256 internal constant IC0_Y = 0x223a6a7dbcf7d785c67f2c87468b54b3e30d6686fcaf078f50fbd7c0f8d0fb3a;

    uint256 internal constant IC1_X = 0x0921e6d9490d813c4e4a75cbae88a78c167101beb80405a1bf67669f72768e4a;
    uint256 internal constant IC1_Y = 0x1d5579f01788c2fd54db704448ad41ed8f5b25179bbdb54ee49e1ef2cd5569ed;

    uint256 internal constant IC2_X = 0x2d7c7dd01c5ccdb7c4cd1a9248fe992182e4a480720a5209c5610055cbc0fa46;
    uint256 internal constant IC2_Y = 0x045e2565dcc9ee9bc5a25eb392364eb0a539ccc5c8aed0f9aa58b662e2d5d9cf;

    uint256 internal constant IC3_X = 0x0e6ed38bbe6ed1cfc2b2fb431255c5fbcbc6ac487d2ef7cbc5584e60944f1cca;
    uint256 internal constant IC3_Y = 0x0ed2b6d559e83f7e2eb9ef4b9564363d6ebb18ffce122feb1ef06b44be087f5f;

    uint256 internal constant IC4_X = 0x0224b7ad1d70325fe66e40ca1928e3d7e684aac431c4f74cb8526da9ad3f8313;
    uint256 internal constant IC4_Y = 0x2e271590d65ad04daaaaf81c0d0aed78279441f3cdc6dc64d246440cceadaef8;

    uint256 internal constant IC5_X = 0x2e0d27ef02fd4ef27b84e1eda7e4f2d149a52d7b5e3c76e08141e4b8abc0084f;
    uint256 internal constant IC5_Y = 0x0e91cfc371f42099db145027b880c03ca948a821d809be51053ecf30aa255f2e;


    
    error PairingFailed();
    error InvalidPublicInput();
    
    /// @notice Verify a Groth16 proof
    /// @param proof [A.x, A.y, B.x1, B.x0, B.y1, B.y0, C.x, C.y]
    /// @param publicInputs [merkleRoot, nullifierHash, signalHash, externalNullifier, treeDepth]
    function verifyProof(
        uint256[8] calldata proof,
        uint256[5] calldata publicInputs
    ) external view returns (bool) {
        // Validate public inputs are in field
        for (uint256 i = 0; i < 5; i++) {
            if (publicInputs[i] >= Q) revert InvalidPublicInput();
        }
        
        // Compute IC aggregation: IC0 + sum(publicInputs[i] * IC[i+1])
        uint256[2] memory ic;
        ic[0] = IC0_X;
        ic[1] = IC0_Y;
        
        // Add weighted IC points
        ic = _ecAdd(ic, _ecMul([IC1_X, IC1_Y], publicInputs[0]));
        ic = _ecAdd(ic, _ecMul([IC2_X, IC2_Y], publicInputs[1]));
        ic = _ecAdd(ic, _ecMul([IC3_X, IC3_Y], publicInputs[2]));
        ic = _ecAdd(ic, _ecMul([IC4_X, IC4_Y], publicInputs[3]));
        ic = _ecAdd(ic, _ecMul([IC5_X, IC5_Y], publicInputs[4]));
        
        // Pairing check: e(-A, B) * e(alpha, beta) * e(IC, gamma) * e(C, delta) == 1
        // Rearranged: e(A, B) == e(alpha, beta) * e(IC, gamma) * e(C, delta)
        
        uint256[24] memory input;
        
        // -A (negate y coordinate)
        input[0] = proof[0];
        input[1] = P - proof[1];
        // B - proof has (x_im, x_re, y_im, y_re), EVM expects same order
        input[2] = proof[2]; // B.x_im
        input[3] = proof[3]; // B.x_re
        input[4] = proof[4]; // B.y_im
        input[5] = proof[5]; // B.y_re
        
        // alpha
        input[6] = ALPHA_X;
        input[7] = ALPHA_Y;
        // beta - stored as (x_im, x_re, y_im, y_re)
        input[8] = BETA_X1;
        input[9] = BETA_X2;
        input[10] = BETA_Y1;
        input[11] = BETA_Y2;
        
        // IC aggregation
        input[12] = ic[0];
        input[13] = ic[1];
        // gamma - stored as (x_im, x_re, y_im, y_re)
        input[14] = GAMMA_X1;
        input[15] = GAMMA_X2;
        input[16] = GAMMA_Y1;
        input[17] = GAMMA_Y2;
        
        // C
        input[18] = proof[6];
        input[19] = proof[7];
        // delta - stored as (x_im, x_re, y_im, y_re)
        input[20] = DELTA_X1;
        input[21] = DELTA_X2;
        input[22] = DELTA_Y1;
        input[23] = DELTA_Y2;
        
        uint256[1] memory result;
        bool success;
        
        assembly {
            success := staticcall(sub(gas(), 2000), 8, input, 768, result, 32)
        }
        
        if (!success) revert PairingFailed();
        
        return result[0] == 1;
    }
    
    function _ecMul(uint256[2] memory p, uint256 s) internal view returns (uint256[2] memory r) {
        uint256[3] memory input;
        input[0] = p[0];
        input[1] = p[1];
        input[2] = s;
        
        assembly {
            if iszero(staticcall(sub(gas(), 2000), 7, input, 96, r, 64)) {
                revert(0, 0)
            }
        }
    }
    
    function _ecAdd(uint256[2] memory p1, uint256[2] memory p2) internal view returns (uint256[2] memory r) {
        uint256[4] memory input;
        input[0] = p1[0];
        input[1] = p1[1];
        input[2] = p2[0];
        input[3] = p2[1];
        
        assembly {
            if iszero(staticcall(sub(gas(), 2000), 6, input, 128, r, 64)) {
                revert(0, 0)
            }
        }
    }
}
