"""
QTT-GA: Geometric Algebra with QTT Compression

Layer 26 of TENSOR GENESIS Protocol

Geometric Algebra (Clifford Algebra) provides a unified mathematical
framework for geometry, physics, and computing. This module implements
GA with QTT compression enabling operations on exponentially large
multivector spaces.

MATHEMATICAL FOUNDATION:
========================

Clifford Algebra Cl(p,q,r):
- Generated by orthonormal basis {e₁, ..., eₙ} where n = p + q + r
- Signature: p positive, q negative, r zero (degenerate)
- Dimension: 2ⁿ for n generators

Geometric Product: ab = a·b + a∧b
- Inner product (contraction)
- Outer product (wedge)
- Full geometric product combines both

Key Structures:
- Scalars: grade 0
- Vectors: grade 1
- Bivectors: grade 2 (oriented planes, rotations)
- Trivectors: grade 3 (oriented volumes)
- Pseudoscalars: grade n

Rotors: R = exp(-θB/2) for bivector B
- Rotation: v' = RvR̃
- Compose: R₁₂ = R₂R₁

Conformal GA (CGA):
- Embeds Euclidean space in null cone
- Unified treatment of points, lines, planes, circles, spheres
- Transformations via versors

QTT INNOVATION:
===============
Multivector has 2ⁿ components — perfect for QTT!
For n=40 basis vectors: 2⁴⁰ components impossible classically.
QTT represents in O(n·r²) parameters.

Copyright (c) 2026 Tigantic Holdings LLC. All Rights Reserved.
"""

from tensornet.genesis.ga.multivector import (
    CliffordAlgebra,
    Multivector,
    scalar,
    vector,
    bivector,
    pseudoscalar,
)

from tensornet.genesis.ga.products import (
    geometric_product,
    inner_product,
    outer_product,
    left_contraction,
    right_contraction,
    scalar_product,
    commutator_product,
    regressive_product,
)

from tensornet.genesis.ga.operations import (
    reverse,
    grade_involution,
    clifford_conjugate,
    magnitude,
    normalize,
    inverse,
    grade_projection,
    even_part,
    odd_part,
    dual,
)

from tensornet.genesis.ga.rotors import (
    rotor_from_bivector,
    rotor_from_angle_plane,
    rotor_from_vectors,
    apply_rotor,
    rotor_log,
    rotor_sqrt,
    interpolate_rotors,
    compose_rotors,
)

from tensornet.genesis.ga.cga import (
    ConformalGA,
    point_to_cga,
    cga_to_point,
    cga_line,
    cga_plane,
    cga_circle,
    cga_sphere,
    meet,
    join,
    distance_point_to_point,
)

from tensornet.genesis.ga.qtt_multivector import (
    QTTMultivector,
    qtt_geometric_product,
    qtt_grade_projection,
)

__all__ = [
    # Algebra and Multivector
    "CliffordAlgebra",
    "Multivector",
    "scalar",
    "vector",
    "bivector",
    "pseudoscalar",
    # Products
    "geometric_product",
    "inner_product",
    "outer_product",
    "left_contraction",
    "right_contraction",
    "scalar_product",
    "commutator_product",
    "regressive_product",
    # Operations
    "reverse",
    "grade_involution",
    "clifford_conjugate",
    "magnitude",
    "normalize",
    "inverse",
    "grade_projection",
    "even_part",
    "odd_part",
    "dual",
    # Rotors
    "rotor_from_bivector",
    "rotor_from_angle_plane",
    "rotor_from_vectors",
    "apply_rotor",
    "rotor_log",
    "rotor_sqrt",
    "interpolate_rotors",
    "compose_rotors",
    # Conformal GA
    "ConformalGA",
    "point_to_cga",
    "cga_to_point",
    "cga_line",
    "cga_plane",
    "cga_circle",
    "cga_sphere",
    "meet",
    "join",
    "distance_point_to_point",
    # QTT Operations
    "QTTMultivector",
    "qtt_geometric_product",
    "qtt_grade_projection",
]
