// SPDX-License-Identifier: PROPRIETARY
// Copyright (c) 2026 Tigantic Holdings LLC. All Rights Reserved.
pragma solidity ^0.8.20;

/**
 * @title HyperTensorBindingVerifier
 * @notice On-chain verifier for ZK binding affinity proofs.
 * @dev Verifies Groth16-style proofs generated by HyperTensor's
 *      physics pipeline. Proof structure matches the Halo2 circuit
 *      layout from fluidelite_circuits.
 *
 * Proof structure:
 *   - pi_a: G1 point (proof element A)
 *   - pi_b: G2 point (proof element B)
 *   - pi_c: G1 point (proof element C)
 *   - public_inputs: [grid_root, threshold, energy_commitment]
 *
 * The verifier checks:
 *   1. Pairing equation: e(pi_a, pi_b) = e(alpha, beta) * e(vk_x, gamma) * e(pi_c, delta)
 *   2. Public input binding: vk_x encodes grid_root and threshold
 *   3. Proof of binding minimum below threshold
 */
interface IBindingVerifier {
    /// @notice Submitted proof structure
    struct Proof {
        uint256[2] pi_a;   // G1 point
        uint256[4] pi_b;   // G2 point (two field elements per coordinate)
        uint256[2] pi_c;   // G1 point
    }

    /// @notice Binding affinity claim
    struct BindingClaim {
        bytes32 gridRoot;          // Merkle root of energy grid
        int256  thresholdQ16;      // Q16.16 energy threshold
        bytes32 energyCommitment;  // H(energy || blinding)
        bytes32 moleculeHash;      // H(SMILES) — molecule identity hidden
    }

    /// @notice Verify a binding affinity proof
    /// @param proof The Groth16 proof elements
    /// @param claim The binding claim to verify
    /// @return valid True if the proof verifies
    function verifyBinding(
        Proof calldata proof,
        BindingClaim calldata claim
    ) external view returns (bool valid);

    /// @notice Register a verified binding claim on-chain
    /// @param proof The proof
    /// @param claim The claim
    /// @return claimId Unique identifier for the registered claim
    function registerClaim(
        Proof calldata proof,
        BindingClaim calldata claim
    ) external returns (bytes32 claimId);

    /// @notice Check if a claim has been registered
    /// @param claimId The claim identifier
    /// @return registered True if claim is on-chain
    /// @return timestamp Block timestamp of registration
    function getClaim(bytes32 claimId)
        external view returns (bool registered, uint256 timestamp);

    /// @notice Emitted when a binding claim is verified and registered
    event BindingVerified(
        bytes32 indexed claimId,
        bytes32 indexed moleculeHash,
        int256 thresholdQ16,
        uint256 timestamp
    );
}

/**
 * @title HyperTensorBindingVerifier
 * @notice Production implementation of the binding verifier.
 */
contract HyperTensorBindingVerifier is IBindingVerifier {
    // Verification key (generated from trusted setup)
    uint256[2] public alpha;
    uint256[4] public beta;
    uint256[4] public gamma;
    uint256[4] public delta;
    uint256[2][] public ic;  // Public input verification key points

    // Registered claims
    mapping(bytes32 => uint256) private _claims;

    constructor(
        uint256[2] memory _alpha,
        uint256[4] memory _beta,
        uint256[4] memory _gamma,
        uint256[4] memory _delta,
        uint256[2][] memory _ic
    ) {
        alpha = _alpha;
        beta = _beta;
        gamma = _gamma;
        delta = _delta;
        for (uint i = 0; i < _ic.length; i++) {
            ic.push(_ic[i]);
        }
    }

    function verifyBinding(
        Proof calldata proof,
        BindingClaim calldata claim
    ) external view returns (bool valid) {
        // Compute vk_x from public inputs
        uint256[2] memory vk_x = _computeVkx(claim);

        // Verify Groth16 pairing equation
        // e(pi_a, pi_b) == e(alpha, beta) * e(vk_x, gamma) * e(pi_c, delta)
        valid = _verifyPairing(
            proof.pi_a, proof.pi_b, proof.pi_c,
            vk_x
        );
    }

    function registerClaim(
        Proof calldata proof,
        BindingClaim calldata claim
    ) external returns (bytes32 claimId) {
        require(this.verifyBinding(proof, claim), "Invalid proof");

        claimId = keccak256(abi.encode(
            claim.gridRoot,
            claim.thresholdQ16,
            claim.energyCommitment,
            claim.moleculeHash
        ));

        require(_claims[claimId] == 0, "Claim already registered");
        _claims[claimId] = block.timestamp;

        emit BindingVerified(
            claimId,
            claim.moleculeHash,
            claim.thresholdQ16,
            block.timestamp
        );
    }

    function getClaim(bytes32 claimId)
        external view returns (bool registered, uint256 timestamp)
    {
        timestamp = _claims[claimId];
        registered = timestamp != 0;
    }

    // ── Internal ──────────────────────────────────────────────────────

    function _computeVkx(BindingClaim calldata claim)
        internal view returns (uint256[2] memory vk_x)
    {
        // Linear combination of IC points with public inputs
        // vk_x = IC[0] + input[0]*IC[1] + input[1]*IC[2] + ...
        vk_x = ic[0];
        // Grid root as field element
        uint256 gridInput = uint256(claim.gridRoot) % _PRIME;
        vk_x = _ecAdd(vk_x, _ecMul(ic[1], gridInput));
        // Threshold as field element
        uint256 threshInput = uint256(uint128(int128(claim.thresholdQ16)));
        vk_x = _ecAdd(vk_x, _ecMul(ic[2], threshInput));
        // Energy commitment as field element
        uint256 commitInput = uint256(claim.energyCommitment) % _PRIME;
        vk_x = _ecAdd(vk_x, _ecMul(ic[3], commitInput));
    }

    // BN256 scalar field order (Fr) — used for public input reduction
    uint256 private constant _PRIME =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // BN256 base field prime (Fp) — used for G1 point negation
    uint256 private constant _FIELD_PRIME =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    function _verifyPairing(
        uint256[2] memory a,
        uint256[4] memory b,
        uint256[2] memory c,
        uint256[2] memory vk_x
    ) internal view returns (bool) {
        // Pairing check via EIP-197 precompile
        uint256[24] memory input;
        // -A (negate G1 point: y → Fp - y)
        input[0] = a[0];
        input[1] = _FIELD_PRIME - a[1];
        // B
        input[2] = b[0]; input[3] = b[1];
        input[4] = b[2]; input[5] = b[3];
        // alpha
        input[6] = alpha[0]; input[7] = alpha[1];
        // beta
        input[8] = beta[0]; input[9] = beta[1];
        input[10] = beta[2]; input[11] = beta[3];
        // vk_x
        input[12] = vk_x[0]; input[13] = vk_x[1];
        // gamma
        input[14] = gamma[0]; input[15] = gamma[1];
        input[16] = gamma[2]; input[17] = gamma[3];
        // C
        input[18] = c[0]; input[19] = c[1];
        // delta
        input[20] = delta[0]; input[21] = delta[1];
        input[22] = delta[2]; input[23] = delta[3];

        uint256[1] memory out;
        bool success;
        assembly {
            success := staticcall(gas(), 0x08, input, 768, out, 32)
        }
        return success && out[0] == 1;
    }

    function _ecAdd(uint256[2] memory a, uint256[2] memory b)
        internal view returns (uint256[2] memory c)
    {
        uint256[4] memory input;
        input[0] = a[0]; input[1] = a[1];
        input[2] = b[0]; input[3] = b[1];
        bool success;
        assembly {
            success := staticcall(gas(), 0x06, input, 128, c, 64)
        }
        require(success, "ecAdd failed");
    }

    function _ecMul(uint256[2] memory p, uint256 s)
        internal view returns (uint256[2] memory r)
    {
        uint256[3] memory input;
        input[0] = p[0]; input[1] = p[1]; input[2] = s;
        bool success;
        assembly {
            success := staticcall(gas(), 0x07, input, 96, r, 64)
        }
        require(success, "ecMul failed");
    }
}
