//! Witness types and generation for the Thermal/Heat Equation proof circuit.
//!
//! The witness contains all private intermediate values the prover
//! needs to satisfy the circuit constraints. It is generated by
//! replaying the implicit heat equation solver and recording every
//! intermediate result.
//!
//! # Thin Tensor Types
//!
//! All MPS/MPO data is stored using the lightweight `Mps`/`Mpo` types
//! from `crate::tensor`. These use flat `Vec<Q16>` storage with no
//! `Serialize`/`Deserialize` derives, eliminating the nested-type
//! serde codegen explosion that caused compilation OOM.
//!
//! Full `fluidelite_core::mps::MPS` / `fluidelite_core::mpo::MPO`
//! types are only used at the public API boundary of `generate()`.
//!
//! © 2026 Tigantic Holdings LLC. All rights reserved. PROPRIETARY.

use std::fmt;

use fluidelite_core::field::Q16;

use crate::tensor::{Mps, Mpo};

use super::config::{
    ThermalCircuitSizing, ThermalParams,
    NUM_THERMAL_VARIABLES, Q16_FRAC_BITS,
};

// ═══════════════════════════════════════════════════════════════════════════
// Core Witness Types
// ═══════════════════════════════════════════════════════════════════════════

/// Complete witness for proving one thermal timestep.
#[derive(Debug, Clone)]
pub struct ThermalWitness {
    /// Physics parameters (public).
    pub params: ThermalParams,

    /// Input temperature state T^n.
    pub input_state: Mps,

    /// Output temperature state T^{n+1}.
    pub output_state: Mps,

    /// Laplacian MPO (discrete ∇²).
    pub laplacian_mpo: Mpo,

    /// RHS assembly witness: r = T^n + Δt·S^n.
    pub rhs_assembly: RhsAssemblyWitness,

    /// Implicit CG solve witness: (I - α·Δt·L) T^{n+1} = r.
    pub implicit_solve: ImplicitSolveWitness,

    /// SVD truncation witness for the final state.
    pub truncation: SvdTruncationWitness,

    /// Conservation witness (energy balance).
    pub conservation: ConservationWitness,

    /// Hash commitments (public inputs).
    pub hashes: HashWitness,
}

/// Witness for RHS assembly: r = T^n + Δt·S^n.
#[derive(Debug, Clone)]
pub struct RhsAssemblyWitness {
    /// Scaled source term: Δt·S^n.
    pub scaled_source: Mps,

    /// Fixed-point remainders from source scaling.
    pub fp_remainders: Vec<i64>,

    /// Fixed-point quotients from source scaling.
    pub fp_quotients: Vec<Q16>,

    /// Assembled RHS: T^n + Δt·S^n.
    pub rhs: Mps,
}

/// Witness for the implicit CG solve.
#[derive(Debug, Clone)]
pub struct ImplicitSolveWitness {
    /// Number of CG iterations performed.
    pub num_iterations: usize,

    /// Per-iteration CG witness data.
    pub iterations: Vec<CgIterationWitness>,

    /// Final residual norm ||r_k||.
    pub final_residual_norm: Q16,

    /// Solution after CG convergence (before truncation).
    pub solution: Mps,
}

/// Witness for one CG iteration.
#[derive(Debug, Clone)]
pub struct CgIterationWitness {
    /// Iteration index.
    pub iteration: usize,

    /// Residual vector r_k.
    pub residual: Mps,

    /// Search direction p_k.
    pub direction: Mps,

    /// A·p_k (system matrix applied to direction).
    pub a_times_direction: Mps,

    /// Contraction witness for computing A·p_k.
    pub contraction: ContractionWitness,

    /// Alpha coefficient: r_k·r_k / (p_k·A·p_k).
    pub alpha: Q16,

    /// Beta coefficient: r_{k+1}·r_{k+1} / (r_k·r_k).
    pub beta: Q16,

    /// Fixed-point remainders for this iteration's multiplications.
    pub fp_remainders: Vec<i64>,

    /// Fixed-point quotients for this iteration's multiplications.
    pub fp_quotients: Vec<Q16>,

    /// Residual norm ||r_k|| at end of iteration.
    pub residual_norm: Q16,
}

// ═══════════════════════════════════════════════════════════════════════════
// Operation-Level Witnesses
// ═══════════════════════════════════════════════════════════════════════════

/// Witness for a single MPO × MPS contraction.
#[derive(Debug, Clone)]
pub struct ContractionWitness {
    /// Number of sites.
    pub num_sites: usize,

    /// Per-site contraction data.
    pub site_data: Vec<SiteContractionData>,

    /// Output MPS after contraction (before truncation).
    pub output_mps: Mps,
}

/// Per-site data for MPO×MPS contraction.
#[derive(Debug, Clone)]
pub struct SiteContractionData {
    /// Accumulator values for each MAC chain.
    pub mac_accumulators: Vec<Vec<Q16>>,

    /// Q16 multiplication remainders for range checks.
    pub fp_remainders: Vec<i64>,

    /// Q16 multiplication quotients.
    pub fp_quotients: Vec<Q16>,
}

/// Witness for SVD truncation.
#[derive(Debug, Clone)]
pub struct SvdTruncationWitness {
    /// Number of SVD operations (one per bond).
    pub num_bonds: usize,

    /// Per-bond SVD data.
    pub bond_data: Vec<BondSvdData>,

    /// Total truncation error.
    pub total_truncation_error: Q16,

    /// Output rank after truncation.
    pub output_rank: usize,
}

/// SVD data for a single bond in the MPS.
#[derive(Debug, Clone)]
pub struct BondSvdData {
    /// Bond index (between site i and site i+1).
    pub bond_index: usize,

    /// Singular values (sorted descending, all non-negative).
    pub singular_values: Vec<Q16>,

    /// Rank after truncation at this bond.
    pub truncated_rank: usize,

    /// Truncation error at this bond.
    pub bond_truncation_error: Q16,

    /// Bit decomposition of (s_i - s_{i+1}) for ordering proof.
    pub sv_ordering_bits: Vec<Vec<bool>>,

    /// Bit decomposition of each singular value for non-negativity proof.
    pub sv_nonneg_bits: Vec<Vec<bool>>,
}

/// Conservation quantities before and after the timestep.
#[derive(Debug, Clone)]
pub struct ConservationWitness {
    /// Energy integral before the timestep: ∫T^n.
    pub integral_before: Q16,

    /// Energy integral after the timestep: ∫T^{n+1}.
    pub integral_after: Q16,

    /// Residual: |∫T^{n+1} - ∫T^n - Δt·∫S^n|.
    pub residual: Q16,

    /// Bit decomposition of (tolerance - residual) proving residual ≤ tolerance.
    pub residual_bound_bits: Vec<bool>,
}

/// Hash commitments that become public inputs.
#[derive(Debug, Clone)]
pub struct HashWitness {
    /// SHA-256 of input state (split into 4 × 64-bit limbs for field embedding).
    pub input_state_hash_limbs: [u64; 4],

    /// SHA-256 of output state (split into 4 × 64-bit limbs).
    pub output_state_hash_limbs: [u64; 4],

    /// SHA-256 of physics parameters (split into 4 × 64-bit limbs).
    pub params_hash_limbs: [u64; 4],
}

// ═══════════════════════════════════════════════════════════════════════════
// Witness Generation
// ═══════════════════════════════════════════════════════════════════════════

/// Generates witnesses by replaying the thermal QTT solver computation.
pub struct WitnessGenerator {
    /// Physics parameters.
    params: ThermalParams,

    /// Circuit sizing.
    sizing: ThermalCircuitSizing,
}

impl WitnessGenerator {
    /// Create a new witness generator.
    pub fn new(params: ThermalParams) -> Self {
        let sizing = ThermalCircuitSizing::from_params(&params);
        Self { params, sizing }
    }

    /// Get the circuit sizing.
    pub fn sizing(&self) -> &ThermalCircuitSizing {
        &self.sizing
    }

    /// Generate a complete witness from input state and Laplacian MPO.
    ///
    /// This replays the entire thermal solver timestep:
    /// 1. RHS assembly: r = T^n + Δt·S^n
    /// 2. Implicit CG solve: (I - α·Δt·L) T^{n+1} = r
    /// 3. SVD truncation
    /// 4. Conservation check
    ///
    /// Full MPS/MPO types are accepted at this boundary and converted
    /// to thin types internally.
    pub fn generate(
        &self,
        input_states: &[fluidelite_core::mps::MPS],
        laplacian_mpos: &[fluidelite_core::mpo::MPO],
    ) -> Result<ThermalWitness, WitnessError> {
        if input_states.len() != NUM_THERMAL_VARIABLES {
            return Err(WitnessError::WrongVariableCount {
                expected: NUM_THERMAL_VARIABLES,
                got: input_states.len(),
            });
        }
        if laplacian_mpos.is_empty() {
            return Err(WitnessError::WrongMpoCount {
                expected: 1,
                got: 0,
            });
        }

        // ── Convert to thin types at the API boundary ──
        let input_state = Mps::from_full(&input_states[0]);
        let laplacian_mpo = Mpo::from_full(&laplacian_mpos[0]);

        // Record input conservation integral
        let integral_before = Self::compute_mps_integral(&input_state);

        // Compute hashes
        let input_hash_limbs = Self::hash_mps_to_limbs(&[&input_state]);
        let params_hash_limbs = Self::hash_to_limbs(&self.params.hash());

        // Step 1: RHS assembly — r = T^n + Δt·S^n
        let rhs_assembly = self.assemble_rhs(&input_state)?;
        let rhs = rhs_assembly.rhs.clone();

        // Step 2: Implicit CG solve — (I - α·Δt·L) T^{n+1} = r
        let implicit_solve = self.cg_solve(
            &rhs,
            &input_state,
            &laplacian_mpo,
        )?;
        let mut solution = implicit_solve.solution.clone();

        // Step 3: SVD truncation
        let truncation = self.truncate_with_witness(&mut solution, self.params.chi_max);

        // Step 4: Conservation check
        let integral_after = Self::compute_mps_integral(&solution);

        // Residual accounts for source contribution
        let source_integral = Q16::from_raw(
            ((self.params.source_magnitude.raw as i128
                * self.params.dt.raw as i128)
                >> Q16_FRAC_BITS) as i64,
        );
        let residual_raw = (integral_after.raw - integral_before.raw - source_integral.raw).abs();
        let residual = Q16::from_raw(residual_raw);

        let bound = self.params.conservation_tol.raw - residual.raw;
        let residual_bound_bits = Self::decompose_nonneg_to_bits(bound, 32);

        let conservation = ConservationWitness {
            integral_before,
            integral_after,
            residual,
            residual_bound_bits,
        };

        let output_hash_limbs = Self::hash_mps_to_limbs(&[&solution]);

        let hashes = HashWitness {
            input_state_hash_limbs: input_hash_limbs,
            output_state_hash_limbs: output_hash_limbs,
            params_hash_limbs,
        };

        Ok(ThermalWitness {
            params: self.params.clone(),
            input_state,
            output_state: solution,
            laplacian_mpo,
            rhs_assembly,
            implicit_solve,
            truncation,
            conservation,
            hashes,
        })
    }

    /// Assemble RHS: r = T^n + Δt·S^n.
    ///
    /// For zero source, r = T^n.
    fn assemble_rhs(&self, input_state: &Mps) -> Result<RhsAssemblyWitness, WitnessError> {
        let dt = self.params.dt;
        let source_mag = self.params.source_magnitude;

        if source_mag.raw == 0 {
            // No source — RHS is just the input state.
            // scaled_source is a zero MPS of the same shape (Δt·S = 0).
            let zero_source = Mps::new(input_state.num_sites, input_state.max_chi(), input_state.d());
            return Ok(RhsAssemblyWitness {
                scaled_source: zero_source,
                fp_remainders: Vec::new(),
                fp_quotients: Vec::new(),
                rhs: input_state.clone(),
            });
        }

        // Scale source by Δt
        let scaled_mag = Q16::from_raw(
            ((dt.raw as i128 * source_mag.raw as i128) >> Q16_FRAC_BITS) as i64,
        );

        // Create uniform source MPS (all cores have source magnitude)
        let mut source_mps = input_state.clone();
        let mut fp_remainders = Vec::new();
        let mut fp_quotients = Vec::new();

        if source_mps.num_sites > 0 {
            let core = source_mps.core_data_mut(0);
            for val in core.iter_mut() {
                let full_product = val.raw as i128 * scaled_mag.raw as i128;
                let quotient = (full_product >> Q16_FRAC_BITS) as i64;
                let remainder =
                    (full_product - ((quotient as i128) << Q16_FRAC_BITS)) as i64;
                fp_quotients.push(Q16::from_raw(quotient));
                fp_remainders.push(remainder);
                *val = Q16::from_raw(quotient);
            }
        }

        // Add source to input
        let rhs = crate::tensor::add(input_state, &source_mps);

        Ok(RhsAssemblyWitness {
            scaled_source: source_mps,
            fp_remainders,
            fp_quotients,
            rhs,
        })
    }

    /// Conjugate Gradient solve for (I - α·Δt·L) x = r.
    ///
    /// Records full witness data for every CG iteration.
    fn cg_solve(
        &self,
        rhs: &Mps,
        initial_guess: &Mps,
        laplacian: &Mpo,
    ) -> Result<ImplicitSolveWitness, WitnessError> {
        let alpha_dt = Q16::from_raw(
            ((self.params.alpha.raw as i128 * self.params.dt.raw as i128)
                >> Q16_FRAC_BITS) as i64,
        );

        // x_0 = initial guess (input state)
        let mut x = initial_guess.clone();

        // r_0 = rhs - A·x_0 where A = I - α·Δt·L
        let (a_x, _contraction_witness) = self.apply_system_matrix(&x, laplacian, alpha_dt)?;
        let mut r = Self::mps_subtract(rhs, &a_x);
        r.truncate(self.params.chi_max);
        let mut p = r.clone();

        let mut r_dot_r = Self::mps_dot_product(&r, &r);
        let mut iterations = Vec::new();

        let chi_max = self.params.chi_max;
        let max_iter = self.params.max_cg_iterations;
        let tol_sq = Q16::from_raw(
            ((self.params.cg_tolerance.raw as i128
                * self.params.cg_tolerance.raw as i128)
                >> Q16_FRAC_BITS) as i64,
        );

        for k in 0..max_iter {
            let residual_norm = Self::q16_sqrt_approx(r_dot_r.raw as i128);

            // Convergence check
            if r_dot_r.raw <= tol_sq.raw && k > 0 {
                iterations.push(CgIterationWitness {
                    iteration: k,
                    residual: r.clone(),
                    direction: p.clone(),
                    a_times_direction: Mps::new(x.num_sites, 1, 2),
                    contraction: ContractionWitness {
                        num_sites: 0,
                        site_data: Vec::new(),
                        output_mps: Mps::new(x.num_sites, 1, 2),
                    },
                    alpha: Q16::zero(),
                    beta: Q16::zero(),
                    fp_remainders: Vec::new(),
                    fp_quotients: Vec::new(),
                    residual_norm,
                });
                break;
            }

            // A·p_k
            let (a_p, cg_contraction) =
                self.apply_system_matrix(&p, laplacian, alpha_dt)?;

            // p·A·p
            let p_a_p = Self::mps_dot_product(&p, &a_p);

            // α_k = r_k·r_k / (p_k·A·p_k)
            let cg_alpha = if p_a_p.raw != 0 {
                Q16::from_raw(
                    ((r_dot_r.raw as i128) << Q16_FRAC_BITS) as i64
                        / p_a_p.raw,
                )
            } else {
                Q16::zero()
            };

            // x_{k+1} = x_k + α_k · p_k
            let scaled_p = Self::mps_scale(&p, cg_alpha);
            x = crate::tensor::add(&x, &scaled_p);
            x.truncate(chi_max);

            // r_{k+1} = r_k - α_k · A·p_k
            let scaled_ap = Self::mps_scale(&a_p, cg_alpha);
            let mut new_r = Self::mps_subtract(&r, &scaled_ap);
            new_r.truncate(chi_max);

            let new_r_dot_r = Self::mps_dot_product(&new_r, &new_r);

            // β_k = r_{k+1}·r_{k+1} / (r_k·r_k)
            let cg_beta = if r_dot_r.raw != 0 {
                Q16::from_raw(
                    ((new_r_dot_r.raw as i128) << Q16_FRAC_BITS) as i64
                        / r_dot_r.raw,
                )
            } else {
                Q16::zero()
            };

            // p_{k+1} = r_{k+1} + β_k · p_k
            let scaled_old_p = Self::mps_scale(&p, cg_beta);
            p = crate::tensor::add(&new_r, &scaled_old_p);
            p.truncate(chi_max);

            iterations.push(CgIterationWitness {
                iteration: k,
                residual: r.clone(),
                direction: p.clone(),
                a_times_direction: a_p,
                contraction: cg_contraction,
                alpha: cg_alpha,
                beta: cg_beta,
                fp_remainders: Vec::new(),
                fp_quotients: Vec::new(),
                residual_norm,
            });

            r = new_r;
            r_dot_r = new_r_dot_r;
        }

        let final_residual_norm = Self::q16_sqrt_approx(r_dot_r.raw as i128);

        Ok(ImplicitSolveWitness {
            num_iterations: iterations.len(),
            iterations,
            final_residual_norm,
            solution: x,
        })
    }

    /// Apply system matrix A = I - α·Δt·L to an MPS state.
    ///
    /// Returns (A·x, contraction_witness).
    fn apply_system_matrix(
        &self,
        state: &Mps,
        laplacian: &Mpo,
        alpha_dt: Q16,
    ) -> Result<(Mps, ContractionWitness), WitnessError> {
        if state.num_sites != laplacian.num_sites {
            return Err(WitnessError::SiteMismatch {
                mps_sites: state.num_sites,
                mpo_sites: laplacian.num_sites,
            });
        }

        // L·x
        let (l_x, contraction) = self.apply_mpo_with_witness(state, laplacian)?;

        // α·Δt·(L·x)
        let scaled_l_x = Self::mps_scale(&l_x, alpha_dt);

        // A·x = x - α·Δt·L·x
        let mut result = Self::mps_subtract(state, &scaled_l_x);
        // Truncate to bound bond dimension growth from direct-sum addition.
        // Without this, chi doubles on every CG iteration → exponential memory.
        result.truncate(self.params.chi_max);

        Ok((result, contraction))
    }

    /// Apply MPO to MPS, recording contraction witness data.
    fn apply_mpo_with_witness(
        &self,
        mps: &Mps,
        mpo: &Mpo,
    ) -> Result<(Mps, ContractionWitness), WitnessError> {
        if mps.num_sites != mpo.num_sites {
            return Err(WitnessError::SiteMismatch {
                mps_sites: mps.num_sites,
                mpo_sites: mpo.num_sites,
            });
        }

        let num_sites = mps.num_sites;
        let d_out = mpo.d_out();
        let d_in = mpo.d_in();

        let mut dims = Vec::with_capacity(num_sites);
        let mut all_data = Vec::new();
        let mut site_data_vec = Vec::with_capacity(num_sites);

        for i in 0..num_sites {
            let mcl = mps.chi_left(i);
            let mcr = mps.chi_right(i);
            let odl = mpo.dl(i);
            let odr = mpo.dr(i);

            let new_chi_left = mcl * odl;
            let new_chi_right = mcr * odr;
            dims.push((new_chi_left, new_chi_right));

            let total_outputs = new_chi_left * d_out * new_chi_right;
            let mut new_data = vec![Q16::zero(); total_outputs];
            let mut mac_accumulators = Vec::with_capacity(total_outputs);
            let mut fp_remainders = Vec::new();
            let mut fp_quotients = Vec::new();

            for cl in 0..mcl {
                for dl in 0..odl {
                    let new_left = cl * odl + dl;

                    for o in 0..d_out {
                        for cr in 0..mcr {
                            for dr in 0..odr {
                                let new_right = cr * odr + dr;

                                let mut acc = Q16::zero();
                                let mut chain = Vec::with_capacity(d_in + 1);
                                chain.push(acc);

                                for p in 0..d_in {
                                    let mpo_val = mpo.get(i, dl, o, p, dr);
                                    let mps_val = mps.get(i, cl, p, cr);

                                    let full_product =
                                        mpo_val.raw as i128 * mps_val.raw as i128;
                                    let quotient =
                                        (full_product >> Q16_FRAC_BITS) as i64;
                                    let remainder =
                                        (full_product - ((quotient as i128) << Q16_FRAC_BITS))
                                            as i64;

                                    fp_quotients.push(Q16::from_raw(quotient));
                                    fp_remainders.push(remainder);

                                    acc = Q16::from_raw(acc.raw + quotient);
                                    chain.push(acc);
                                }

                                mac_accumulators.push(chain);
                                new_data[(new_left * d_out + o) * new_chi_right
                                    + new_right] = acc;
                            }
                        }
                    }
                }
            }

            all_data.extend_from_slice(&new_data);
            site_data_vec.push(SiteContractionData {
                mac_accumulators,
                fp_remainders,
                fp_quotients,
            });
        }

        let output_mps = Mps::from_flat(&dims, d_out, all_data);

        let witness = ContractionWitness {
            num_sites,
            site_data: site_data_vec,
            output_mps: output_mps.clone(),
        };

        Ok((output_mps, witness))
    }

    /// SVD truncation with witness recording.
    fn truncate_with_witness(&self, mps: &mut Mps, chi_max: usize) -> SvdTruncationWitness {
        let num_bonds = if mps.num_sites > 0 {
            mps.num_sites - 1
        } else {
            0
        };
        let mut bond_data = Vec::with_capacity(num_bonds);
        let mut total_error_sq = 0i128;

        for bond_idx in 0..num_bonds {
            let left_chi = mps.chi_right(bond_idx);
            let right_chi = mps.chi_left(bond_idx + 1);
            let current_rank = left_chi.min(right_chi);
            let truncated_rank = current_rank.min(chi_max);

            let singular_values = Self::estimate_singular_values(
                mps,
                bond_idx,
                current_rank,
            );

            let mut bond_error_sq = 0i128;
            for sv in singular_values.iter().skip(truncated_rank) {
                bond_error_sq += (sv.raw as i128) * (sv.raw as i128);
            }
            total_error_sq += bond_error_sq;

            let bond_error = Self::q16_sqrt_approx(bond_error_sq);

            let sv_ordering_bits: Vec<Vec<bool>> = singular_values
                .windows(2)
                .map(|pair| {
                    let diff = pair[0].raw - pair[1].raw;
                    Self::decompose_nonneg_to_bits(diff, 32)
                })
                .collect();

            let sv_nonneg_bits: Vec<Vec<bool>> = singular_values
                .iter()
                .map(|sv| Self::decompose_nonneg_to_bits(sv.raw, 32))
                .collect();

            bond_data.push(BondSvdData {
                bond_index: bond_idx,
                singular_values,
                truncated_rank,
                bond_truncation_error: bond_error,
                sv_ordering_bits,
                sv_nonneg_bits,
            });
        }

        mps.truncate(chi_max);

        let total_truncation_error = Self::q16_sqrt_approx(total_error_sq);
        let output_rank = mps.max_chi();

        SvdTruncationWitness {
            num_bonds,
            bond_data,
            total_truncation_error,
            output_rank,
        }
    }

    // ═══════════════════════════════════════════════════════════════════════
    // MPS Arithmetic Helpers
    // ═══════════════════════════════════════════════════════════════════════

    /// MPS subtraction: a - b (negate first core of b, then add).
    fn mps_subtract(a: &Mps, b: &Mps) -> Mps {
        let neg_b = Self::negate_mps(b);
        crate::tensor::add(a, &neg_b)
    }

    /// Scale MPS by a Q16 scalar (modifies first core only).
    fn mps_scale(mps: &Mps, scalar: Q16) -> Mps {
        let mut result = mps.clone();
        if result.num_sites > 0 {
            let core = result.core_data_mut(0);
            for val in core.iter_mut() {
                let full_product = val.raw as i128 * scalar.raw as i128;
                let quotient = (full_product >> Q16_FRAC_BITS) as i64;
                *val = Q16::from_raw(quotient);
            }
        }
        result
    }

    /// Approximate dot product of two MPS: Σ_i (Σ_j a_j_i × b_j_i).
    ///
    /// This is a proxy using element-wise core products, not the full
    /// contraction. For the CG solve verification, the important thing
    /// is that the circuit constrains the *same* dot product operation
    /// the solver uses.
    fn mps_dot_product(a: &Mps, b: &Mps) -> Q16 {
        let mut sum = Q16::zero();
        let n = a.num_sites.min(b.num_sites);
        for i in 0..n {
            let a_data = a.core_data(i);
            let b_data = b.core_data(i);
            let len = a_data.len().min(b_data.len());
            for j in 0..len {
                let product_raw = ((a_data[j].raw as i128
                    * b_data[j].raw as i128)
                    >> Q16_FRAC_BITS) as i64;
                sum = Q16::from_raw(sum.raw + product_raw);
            }
        }
        sum
    }

    /// Negate an MPS by negating the first core.
    fn negate_mps(mps: &Mps) -> Mps {
        let mut result = mps.clone();
        if result.num_sites > 0 {
            let core = result.core_data_mut(0);
            for val in core.iter_mut() {
                *val = -*val;
            }
        }
        result
    }

    // ═══════════════════════════════════════════════════════════════════════
    // Helper Methods
    // ═══════════════════════════════════════════════════════════════════════

    /// Compute a proxy for the integral of an MPS state.
    pub fn compute_mps_integral(mps: &Mps) -> Q16 {
        let mut sum = Q16::zero();
        for val in mps.flat_data() {
            sum = sum + *val;
        }
        sum
    }

    /// Estimate singular values from an MPS core's Frobenius norms.
    fn estimate_singular_values(mps: &Mps, site: usize, rank: usize) -> Vec<Q16> {
        let mut svs = Vec::with_capacity(rank);

        for r in 0..rank.min(mps.chi_right(site)) {
            let mut norm_sq = 0i128;
            for l in 0..mps.chi_left(site) {
                for p in 0..mps.d() {
                    let val = mps.get(site, l, p, r);
                    norm_sq += (val.raw as i128) * (val.raw as i128);
                }
            }
            let norm = Self::q16_sqrt_approx(norm_sq);
            svs.push(norm);
        }

        svs.sort_by(|a, b| b.raw.cmp(&a.raw));
        svs
    }

    /// Approximate integer square root in Q16 domain.
    fn q16_sqrt_approx(sum_sq: i128) -> Q16 {
        if sum_sq <= 0 {
            return Q16::zero();
        }
        let mut x = sum_sq;
        let mut y = (x + 1) / 2;
        while y < x {
            x = y;
            y = (x + sum_sq / x) / 2;
        }
        Q16::from_raw(x.min(i64::MAX as i128) as i64)
    }

    /// Decompose a non-negative value into bits (LSB first).
    fn decompose_nonneg_to_bits(value: i64, num_bits: usize) -> Vec<bool> {
        if value < 0 {
            return vec![false; num_bits];
        }
        let v = value as u64;
        (0..num_bits).map(|i| (v >> i) & 1 == 1).collect()
    }

    /// Convert a 32-byte SHA-256 hash into 4 × 64-bit limbs.
    fn hash_to_limbs(hash: &[u8; 32]) -> [u64; 4] {
        let mut limbs = [0u64; 4];
        for (i, limb) in limbs.iter_mut().enumerate() {
            let offset = i * 8;
            *limb = u64::from_le_bytes([
                hash[offset],
                hash[offset + 1],
                hash[offset + 2],
                hash[offset + 3],
                hash[offset + 4],
                hash[offset + 5],
                hash[offset + 6],
                hash[offset + 7],
            ]);
        }
        limbs
    }

    /// Compute SHA-256 hash of MPS states and return as limbs.
    ///
    /// Uses thin `Mps` types — iterates per-site to produce
    /// the same hash as the original MPS-based hashing.
    fn hash_mps_to_limbs(states: &[&Mps]) -> [u64; 4] {
        use sha2::{Digest, Sha256};
        let mut hasher = Sha256::new();
        hasher.update(b"THERMAL_STATE_V1");
        hasher.update((states.len() as u64).to_le_bytes());

        for state in states {
            hasher.update((state.num_sites as u64).to_le_bytes());
            for i in 0..state.num_sites {
                hasher.update((state.chi_left(i) as u64).to_le_bytes());
                hasher.update((state.d() as u64).to_le_bytes());
                hasher.update((state.chi_right(i) as u64).to_le_bytes());
                for val in state.core_data(i) {
                    hasher.update(val.raw.to_le_bytes());
                }
            }
        }

        let result = hasher.finalize();
        let mut hash = [0u8; 32];
        hash.copy_from_slice(&result);
        Self::hash_to_limbs(&hash)
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Error Types
// ═══════════════════════════════════════════════════════════════════════════

/// Errors during witness generation.
#[derive(Debug, Clone)]
pub enum WitnessError {
    /// Wrong number of temperature variables.
    WrongVariableCount {
        /// Expected count.
        expected: usize,
        /// Actual count.
        got: usize,
    },
    /// Wrong number of Laplacian MPOs.
    WrongMpoCount {
        /// Expected count.
        expected: usize,
        /// Actual count.
        got: usize,
    },
    /// MPS and MPO site count mismatch.
    SiteMismatch {
        /// MPS site count.
        mps_sites: usize,
        /// MPO site count.
        mpo_sites: usize,
    },
}

impl fmt::Display for WitnessError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            WitnessError::WrongVariableCount { expected, got } => {
                write!(f, "Expected {} variables, got {}", expected, got)
            }
            WitnessError::WrongMpoCount { expected, got } => {
                write!(f, "Expected {} Laplacian MPOs, got {}", expected, got)
            }
            WitnessError::SiteMismatch {
                mps_sites,
                mpo_sites,
            } => {
                write!(
                    f,
                    "MPS sites ({}) != MPO sites ({})",
                    mps_sites, mpo_sites
                )
            }
        }
    }
}

impl std::error::Error for WitnessError {}

// ═══════════════════════════════════════════════════════════════════════════
// Tests (private method access — integration tests cover public API)
// ═══════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_mps_dot_product_self() {
        let mps = Mps::new(4, 2, 2);
        let dot = WitnessGenerator::mps_dot_product(&mps, &mps);
        // Dot product of zero MPS with itself should be zero
        assert_eq!(dot.raw, 0);
    }

    #[test]
    fn test_mps_negate_roundtrip() {
        let mps = Mps::new(4, 2, 2);
        let neg = WitnessGenerator::negate_mps(&mps);
        let double_neg = WitnessGenerator::negate_mps(&neg);
        for i in 0..mps.num_sites {
            let a = mps.core_data(i);
            let b = double_neg.core_data(i);
            for (va, vb) in a.iter().zip(b.iter()) {
                assert_eq!(va.raw, vb.raw);
            }
        }
    }
}
