"""
The Ontic Engine — Where Physics Are Compiled, Executed, and Constrained
========================================================================

The computational heart of The Physics OS.  A pure PyTorch implementation
of Matrix Product States (MPS) and Matrix Product Operators (MPO) for
many-body physics and CFD, with a register-based QTT VM that compiles
domain specifications into compression-native bytecode.

Tigantic Holdings LLC · DBA HolonomiX · The Physics OS · The Ontic Engine

Core Components:
    MPS     - Matrix Product State representation
    MPO     - Matrix Product Operator (Hamiltonians)
    dmrg    - Density Matrix Renormalization Group
    tebd    - Time-Evolving Block Decimation
    tdvp    - Time-Dependent Variational Principle

Hamiltonians:
    heisenberg_mpo  - Heisenberg XXZ chain
    tfim_mpo        - Transverse-field Ising model
    bose_hubbard_mpo - Bose-Hubbard model

Example:
    >>> from tensornet import MPS, heisenberg_mpo, dmrg
    >>> H = heisenberg_mpo(L=10, J=1.0)
    >>> psi = MPS.random(L=10, d=2, chi=32)
    >>> psi, E, info = dmrg(psi, H, num_sweeps=10)
    >>> print(f"Ground state energy: {E:.8f}")
"""

__version__ = "40.0.1"
__author__ = "TiganticLabz"

# Algorithms
from tensornet.algorithms.dmrg import dmrg
from tensornet.algorithms.lanczos import lanczos_ground_state
from tensornet.algorithms.tdvp import TDVPResult, imaginary_time_tdvp, tdvp, tdvp_step
from tensornet.algorithms.tebd import tebd, tebd_step
from tensornet.cfd.boundaries import BCType, BoundaryManager, FlowState

# CFD Module (Phase 2)
from tensornet.cfd.euler_1d import (
                                       Euler1D,
                                       EulerState,
                                       euler_to_mps,
                                       lax_shock_tube_ic,
                                       mps_to_euler,
                                       shu_osher_ic,
                                       sod_shock_tube_ic,
)

# CFD Module (Phase 3 - 2D)
from tensornet.cfd.euler_2d import Euler2D, Euler2DState, oblique_shock_exact, supersonic_wedge_ic
from tensornet.cfd.geometry import ImmersedBoundary, WedgeGeometry
from tensornet.cfd.godunov import exact_riemann, hll_flux, hllc_flux, roe_flux
from tensornet.cfd.limiters import mc_limiter, minmod, superbee, van_leer
from tensornet.cfd.qtt import (
                                       QTTCompressionResult,
                                       euler_to_qtt,
                                       field_to_qtt,
                                       qtt_to_euler,
                                       qtt_to_field,
)

# Utility functions
from tensornet.core.decompositions import qr_positive, svd_truncated
from tensornet.core.mpo import MPO

# Core classes
from tensornet.core.mps import MPS
from tensornet.core.states import ghz_mps, product_mps, random_mps

# Deployment Module (Phase 11)
from tensornet.infra.deployment import (
                                       EmbeddedRuntime,
                                       ExportConfig,
                                       ExportResult,
                                       JetsonConfig,
                                       MemoryProfile,
                                       PowerMode,
                                       TensorRTExporter,
                                       benchmark_inference,
                                       configure_jetson_power,
                                       create_inference_pipeline,
                                       export_to_onnx,
                                       optimize_for_tensorrt,
                                       optimize_memory_layout,
                                       validate_exported_model,
)

# Digital Twin Module (Phase 13)
from tensornet.infra.digital_twin import (
                                       AnomalyDetector,
                                       AutoencoderROM,
                                       DigitalTwin,
                                       DMDModel,
                                       HealthMonitor,
                                       MaintenanceScheduler,
                                       PODModel,
                                       PredictiveMaintenance,
                                       ReducedOrderModel,
                                       RULEstimator,
                                       StateSync,
                                       StateSynchronizer,
                                       StateVector,
                                       StructuralHealth,
                                       SyncConfig,
                                       ThermalHealth,
                                       TwinMode,
                                       TwinStatus,
                                       connect_twins,
                                       create_vehicle_twin,
                                       validate_twin_fidelity,
)

# Distributed Computing Module (Phase 13)
from tensornet.engine.distributed import (
                                       AllReduceOp,
                                       CommPattern,
                                       Communicator,
                                       DistributedScheduler,
                                       DomainConfig,
                                       DomainDecomposition,
                                       DomainSolver,
                                       GPUConfig,
                                       GPUDevice,
                                       GPUManager,
                                       MemoryPool,
                                       ParallelCGSolver,
                                       ParallelConfig,
                                       ParallelGMRESSolver,
                                       SchwarzPreconditioner,
                                       SubdomainInfo,
                                       Task,
                                       TaskConfig,
                                       TaskGraph,
                                       all_reduce,
                                       async_recv,
                                       async_send,
                                       barrier,
                                       broadcast,
                                       compute_ghost_zones,
                                       decompose_domain,
                                       distribute_workload,
                                       exchange_ghost_data,
                                       execute_parallel,
                                       gather,
                                       get_available_gpus,
                                       parallel_solve,
                                       scatter,
                                       schedule_dependency_graph,
                                       select_optimal_device,
)

# Documentation Module (Phase 14)
from tensornet.docs import (
                                       APIExtractor,
                                       ClassDoc,
                                       CodeExample,
                                       ExampleConfig,
                                       ExampleRunner,
                                       FunctionDoc,
                                       GuideBuilder,
                                       GuideSection,
                                       ModuleDoc,
                                       ParameterDoc,
                                       RunnableExample,
                                       SphinxBuilder,
                                       SphinxConfig,
                                       SphinxTheme,
                                       Tutorial,
                                       build_documentation,
                                       create_cfd_tutorial,
                                       create_deployment_guide,
                                       create_getting_started,
                                       create_tensor_network_primer,
                                       extract_examples_from_docstrings,
                                       extract_module_docs,
                                       generate_api_markdown,
                                       generate_api_rst,
                                       generate_conf_py,
                                       validate_example,
)

# Guidance Module (Phase 11)
from tensornet.aerospace.guidance import (
                                       AeroCoefficients,
                                       AtmosphericModel,
                                       ConstraintType,
                                       GuidanceCommand,
                                       GuidanceController,
                                       GuidanceMode,
                                       TrajectoryConfig,
                                       TrajectoryConstraint,
                                       TrajectorySolver,
                                       VehicleState,
                                       bank_angle_guidance,
                                       exponential_atmosphere,
                                       isa_atmosphere,
                                       proportional_navigation,
)

# ML Surrogates Module (Phase 13)
from tensornet.ml.ml_surrogates import (
                                       ActiveLearner,
                                       BayesianUQ,
                                       CFDSurrogate,
                                       DataAugmentor,
                                       DeepONet,
                                       DeepONetConfig,
                                       EnsembleUQ,
                                       EulerPINN,
                                       FNO2d,
                                       FNO3d,
                                       FNOConfig,
                                       MCDropoutUQ,
                                       MLPSurrogate,
                                       MultiInputDeepONet,
                                       NavierStokesPINN,
                                       PhysicsInformedNet,
                                       PINNConfig,
                                       ResNetSurrogate,
                                       SurrogateConfig,
                                       SurrogateTrainer,
                                       TFNO2d,
                                       TrainingConfig,
                                       UncertaintyConfig,
                                       cross_validate,
                                       evaluate_surrogate,
                                       train_surrogate,
)

# Hamiltonians
from tensornet.mps.hamiltonians import (
                                       bose_hubbard_mpo,
                                       heisenberg_mpo,
                                       pauli_matrices,
                                       spin_operators,
                                       tfim_mpo,
                                       xx_mpo,
                                       xyz_mpo,
)

# Simulation Module (Phase 12)
from tensornet.sim.simulation import (  # HIL; Flight Data; Real-Time CFD; Mission Simulation
                                       ActuatorModel,
                                       AeroTable,
                                       AeroTableConfig,
                                       AirDataSensor,
                                       ControlSurface,
                                       FlightRecord,
                                       GPSSensor,
                                       HILConfig,
                                       HILInterface,
                                       HILMode,
                                       IMUSensor,
                                       MissionConfig,
                                       MissionPhase,
                                       MissionResult,
                                       MissionSimulator,
                                       MonteCarloConfig,
                                       RealTimeCFD,
                                       SensorModel,
                                       TelemetryFrame,
                                       ThrustActuator,
                                       TrajectoryReconstruction,
                                       UncertaintyModel,
                                       analyze_dispersion,
                                       build_aero_table,
                                       create_vehicle_actuators,
                                       create_vehicle_sensors,
                                       interpolate_coefficients,
                                       parse_telemetry,
                                       run_monte_carlo,
                                       validate_against_flight,
)

# Validation Module (Phase 15)
from tensornet.sim.validation import (  # Physical validation; Benchmarks; Regression; V&V
                                       AnalyticalValidation,
                                       AnalyticalValidator,
                                       ArrayComparator,
                                       BenchmarkConfig,
                                       BenchmarkResult,
                                       BenchmarkSuite,
                                       BlasiusValidator,
                                       CodeVerification,
                                       ConservationValidator,
                                       EnergyConservationTest,
                                       ExperimentalValidation,
                                       GoldenValue,
                                       GoldenValueStore,
                                       IntegrationVerification,
                                       IsentropicVortexValidator,
                                       MassConservationTest,
                                       MemorySnapshot,
                                       MemoryTracker,
                                       MomentumConservationTest,
                                       ObliqueShockValidator,
                                       PerformanceTimer,
                                       RegressionResult,
                                       RegressionSuite,
                                       RegressionTest,
                                       ScalabilityTest,
                                       SodShockValidator,
                                       StateComparator,
                                       StrongScalingTest,
                                       TensorComparator,
                                       TimerContext,
                                       UncertaintyBand,
                                       UnitVerification,
                                       ValidationCase,
                                       ValidationReport,
                                       ValidationResult,
                                       ValidationSeverity,
                                       ValidationUncertainty,
                                       VVCategory,
                                       VVLevel,
                                       VVPlan,
                                       VVReport,
                                       VVTest,
                                       VVTestResult,
                                       WeakScalingTest,
                                       compare_benchmarks,
                                       generate_vv_report,
                                       run_benchmark,
                                       run_benchmark_suite,
                                       run_full_regression,
                                       run_physical_validation,
                                       run_regression_tests,
                                       run_vv_plan,
                                       update_golden_values,
)

__all__ = [
    # Core
    "MPS",
    "MPO",
    # Algorithms
    "dmrg",
    "tebd",
    "tebd_step",
    "lanczos_ground_state",
    "tdvp",
    "tdvp_step",
    "imaginary_time_tdvp",
    "TDVPResult",
    # Hamiltonians
    "heisenberg_mpo",
    "tfim_mpo",
    "xx_mpo",
    "xyz_mpo",
    "bose_hubbard_mpo",
    "pauli_matrices",
    "spin_operators",
    # Utilities
    "svd_truncated",
    "qr_positive",
    "ghz_mps",
    "product_mps",
    "random_mps",
    # CFD 1D
    "Euler1D",
    "EulerState",
    "euler_to_mps",
    "mps_to_euler",
    "sod_shock_tube_ic",
    "lax_shock_tube_ic",
    "shu_osher_ic",
    "roe_flux",
    "hll_flux",
    "hllc_flux",
    "exact_riemann",
    "minmod",
    "superbee",
    "van_leer",
    "mc_limiter",
    # CFD 2D
    "Euler2D",
    "Euler2DState",
    "supersonic_wedge_ic",
    "oblique_shock_exact",
    "WedgeGeometry",
    "ImmersedBoundary",
    "BCType",
    "FlowState",
    "BoundaryManager",
    # QTT Compression (Phase 5)
    "field_to_qtt",
    "qtt_to_field",
    "euler_to_qtt",
    "qtt_to_euler",
    "QTTCompressionResult",
    # Deployment (Phase 11)
    "ExportConfig",
    "ExportResult",
    "TensorRTExporter",
    "export_to_onnx",
    "optimize_for_tensorrt",
    "validate_exported_model",
    "benchmark_inference",
    "JetsonConfig",
    "MemoryProfile",
    "PowerMode",
    "EmbeddedRuntime",
    "optimize_memory_layout",
    "configure_jetson_power",
    "create_inference_pipeline",
    # Guidance (Phase 11)
    "AtmosphericModel",
    "VehicleState",
    "AeroCoefficients",
    "TrajectoryConfig",
    "TrajectorySolver",
    "isa_atmosphere",
    "exponential_atmosphere",
    "GuidanceMode",
    "ConstraintType",
    "GuidanceCommand",
    "TrajectoryConstraint",
    "GuidanceController",
    "proportional_navigation",
    "bank_angle_guidance",
    # Simulation (Phase 12)
    "HILConfig",
    "HILMode",
    "SensorModel",
    "IMUSensor",
    "GPSSensor",
    "AirDataSensor",
    "ActuatorModel",
    "ControlSurface",
    "ThrustActuator",
    "HILInterface",
    "create_vehicle_sensors",
    "create_vehicle_actuators",
    "TelemetryFrame",
    "FlightRecord",
    "TrajectoryReconstruction",
    "parse_telemetry",
    "validate_against_flight",
    "AeroTableConfig",
    "AeroTable",
    "RealTimeCFD",
    "build_aero_table",
    "interpolate_coefficients",
    "MissionPhase",
    "MissionConfig",
    "UncertaintyModel",
    "MonteCarloConfig",
    "MissionResult",
    "MissionSimulator",
    "run_monte_carlo",
    "analyze_dispersion",
    # Digital Twin (Phase 13)
    "StateSync",
    "StateSynchronizer",
    "SyncConfig",
    "StateVector",
    "PODModel",
    "DMDModel",
    "AutoencoderROM",
    "ReducedOrderModel",
    "HealthMonitor",
    "StructuralHealth",
    "ThermalHealth",
    "AnomalyDetector",
    "RULEstimator",
    "MaintenanceScheduler",
    "PredictiveMaintenance",
    "DigitalTwin",
    "TwinMode",
    "TwinStatus",
    "create_vehicle_twin",
    "connect_twins",
    "validate_twin_fidelity",
    # ML Surrogates (Phase 13)
    "SurrogateConfig",
    "CFDSurrogate",
    "MLPSurrogate",
    "ResNetSurrogate",
    "PINNConfig",
    "PhysicsInformedNet",
    "NavierStokesPINN",
    "EulerPINN",
    "DeepONetConfig",
    "DeepONet",
    "MultiInputDeepONet",
    "FNOConfig",
    "FNO2d",
    "FNO3d",
    "TFNO2d",
    "UncertaintyConfig",
    "EnsembleUQ",
    "MCDropoutUQ",
    "BayesianUQ",
    "TrainingConfig",
    "SurrogateTrainer",
    "DataAugmentor",
    "ActiveLearner",
    "evaluate_surrogate",
    "train_surrogate",
    "cross_validate",
    # Distributed Computing (Phase 13)
    "DomainConfig",
    "DomainDecomposition",
    "SubdomainInfo",
    "decompose_domain",
    "compute_ghost_zones",
    "exchange_ghost_data",
    "GPUConfig",
    "GPUDevice",
    "GPUManager",
    "MemoryPool",
    "get_available_gpus",
    "select_optimal_device",
    "distribute_workload",
    "CommPattern",
    "Communicator",
    "AllReduceOp",
    "async_send",
    "async_recv",
    "barrier",
    "all_reduce",
    "broadcast",
    "scatter",
    "gather",
    "TaskConfig",
    "Task",
    "TaskGraph",
    "DistributedScheduler",
    "schedule_dependency_graph",
    "execute_parallel",
    "ParallelConfig",
    "DomainSolver",
    "ParallelCGSolver",
    "ParallelGMRESSolver",
    "SchwarzPreconditioner",
    "parallel_solve",
    # Documentation (Phase 14)
    "ModuleDoc",
    "ClassDoc",
    "FunctionDoc",
    "ParameterDoc",
    "APIExtractor",
    "extract_module_docs",
    "generate_api_markdown",
    "generate_api_rst",
    "GuideSection",
    "Tutorial",
    "CodeExample",
    "GuideBuilder",
    "create_getting_started",
    "create_cfd_tutorial",
    "create_tensor_network_primer",
    "create_deployment_guide",
    "SphinxConfig",
    "SphinxTheme",
    "SphinxBuilder",
    "generate_conf_py",
    "build_documentation",
    "ExampleConfig",
    "RunnableExample",
    "ExampleRunner",
    "validate_example",
    "extract_examples_from_docstrings",
    # Validation (Phase 15)
    "ConservationValidator",
    "MassConservationTest",
    "MomentumConservationTest",
    "EnergyConservationTest",
    "AnalyticalValidator",
    "SodShockValidator",
    "BlasiusValidator",
    "ObliqueShockValidator",
    "IsentropicVortexValidator",
    "ValidationResult",
    "ValidationSeverity",
    "ValidationReport",
    "run_physical_validation",
    "BenchmarkConfig",
    "BenchmarkResult",
    "BenchmarkSuite",
    "TimerContext",
    "PerformanceTimer",
    "MemoryTracker",
    "MemorySnapshot",
    "ScalabilityTest",
    "WeakScalingTest",
    "StrongScalingTest",
    "run_benchmark",
    "run_benchmark_suite",
    "compare_benchmarks",
    "RegressionTest",
    "RegressionSuite",
    "RegressionResult",
    "GoldenValue",
    "GoldenValueStore",
    "update_golden_values",
    "ArrayComparator",
    "TensorComparator",
    "StateComparator",
    "run_regression_tests",
    "run_full_regression",
    "VVLevel",
    "VVCategory",
    "VVTest",
    "VVTestResult",
    "VVPlan",
    "VVReport",
    "CodeVerification",
    "UnitVerification",
    "IntegrationVerification",
    "ValidationCase",
    "ExperimentalValidation",
    "AnalyticalValidation",
    "UncertaintyBand",
    "ValidationUncertainty",
    "run_vv_plan",
    "generate_vv_report",
]
