"""
TensorNet: Quantum-Inspired Tensor Networks for Computational Physics
======================================================================

A pure PyTorch implementation of Matrix Product States (MPS) and
Matrix Product Operators (MPO) for many-body physics and CFD.

Core Components:
    MPS     - Matrix Product State representation
    MPO     - Matrix Product Operator (Hamiltonians)
    dmrg    - Density Matrix Renormalization Group
    tebd    - Time-Evolving Block Decimation
    tdvp    - Time-Dependent Variational Principle

Hamiltonians:
    heisenberg_mpo  - Heisenberg XXZ chain
    tfim_mpo        - Transverse-field Ising model
    bose_hubbard_mpo - Bose-Hubbard model

Example:
    >>> from tensornet import MPS, heisenberg_mpo, dmrg
    >>> H = heisenberg_mpo(L=10, J=1.0)
    >>> psi = MPS.random(L=10, d=2, chi=32)
    >>> psi, E, info = dmrg(psi, H, num_sweeps=10)
    >>> print(f"Ground state energy: {E:.8f}")
"""

__version__ = "0.1.0"
__author__ = "TiganticLabz"

# Core classes
from tensornet.core.mps import MPS
from tensornet.core.mpo import MPO

# Algorithms
from tensornet.algorithms.dmrg import dmrg
from tensornet.algorithms.tebd import tebd, tebd_step
from tensornet.algorithms.lanczos import lanczos_ground_state
from tensornet.algorithms.tdvp import tdvp, tdvp_step, imaginary_time_tdvp, TDVPResult

# Hamiltonians
from tensornet.mps.hamiltonians import (
    heisenberg_mpo,
    tfim_mpo,
    xx_mpo,
    xyz_mpo,
    bose_hubbard_mpo,
    pauli_matrices,
    spin_operators,
)

# Utility functions
from tensornet.core.decompositions import svd_truncated, qr_positive
from tensornet.core.states import ghz_mps, product_mps, random_mps

# CFD Module (Phase 2)
from tensornet.cfd.euler_1d import (
    Euler1D,
    EulerState,
    euler_to_mps,
    mps_to_euler,
    sod_shock_tube_ic,
    lax_shock_tube_ic,
    shu_osher_ic,
)
from tensornet.cfd.godunov import roe_flux, hll_flux, hllc_flux, exact_riemann
from tensornet.cfd.limiters import minmod, superbee, van_leer, mc_limiter

# CFD Module (Phase 3 - 2D)
from tensornet.cfd.euler_2d import (
    Euler2D,
    Euler2DState,
    supersonic_wedge_ic,
    oblique_shock_exact,
)
from tensornet.cfd.geometry import WedgeGeometry, ImmersedBoundary
from tensornet.cfd.boundaries import BCType, FlowState, BoundaryManager
from tensornet.cfd.qtt import (
    field_to_qtt,
    qtt_to_field,
    euler_to_qtt,
    qtt_to_euler,
    QTTCompressionResult,
)

# Deployment Module (Phase 11)
from tensornet.deployment import (
    ExportConfig,
    ExportResult,
    TensorRTExporter,
    export_to_onnx,
    optimize_for_tensorrt,
    validate_exported_model,
    benchmark_inference,
    JetsonConfig,
    MemoryProfile,
    PowerMode,
    EmbeddedRuntime,
    optimize_memory_layout,
    configure_jetson_power,
    create_inference_pipeline,
)

# Guidance Module (Phase 11)
from tensornet.guidance import (
    AtmosphericModel,
    VehicleState,
    AeroCoefficients,
    TrajectoryConfig,
    TrajectorySolver,
    isa_atmosphere,
    exponential_atmosphere,
    GuidanceMode,
    ConstraintType,
    GuidanceCommand,
    TrajectoryConstraint,
    GuidanceController,
    proportional_navigation,
    bank_angle_guidance,
)

# Simulation Module (Phase 12)
from tensornet.simulation import (
    # HIL
    HILConfig,
    HILMode,
    SensorModel,
    IMUSensor,
    GPSSensor,
    AirDataSensor,
    ActuatorModel,
    ControlSurface,
    ThrustActuator,
    HILInterface,
    create_vehicle_sensors,
    create_vehicle_actuators,
    # Flight Data
    TelemetryFrame,
    FlightRecord,
    TrajectoryReconstruction,
    parse_telemetry,
    validate_against_flight,
    # Real-Time CFD
    AeroTableConfig,
    AeroTable,
    RealTimeCFD,
    build_aero_table,
    interpolate_coefficients,
    # Mission Simulation
    MissionPhase,
    MissionConfig,
    UncertaintyModel,
    MonteCarloConfig,
    MissionResult,
    MissionSimulator,
    run_monte_carlo,
    analyze_dispersion,
)

# Digital Twin Module (Phase 13)
from tensornet.digital_twin import (
    StateSync,
    StateSynchronizer,
    SyncConfig,
    StateVector,
    PODModel,
    DMDModel,
    AutoencoderROM,
    ReducedOrderModel,
    HealthMonitor,
    StructuralHealth,
    ThermalHealth,
    AnomalyDetector,
    RULEstimator,
    MaintenanceScheduler,
    PredictiveMaintenance,
    DigitalTwin,
    TwinMode,
    TwinStatus,
    create_vehicle_twin,
    connect_twins,
    validate_twin_fidelity,
)

# ML Surrogates Module (Phase 13)
from tensornet.ml_surrogates import (
    SurrogateConfig,
    CFDSurrogate,
    MLPSurrogate,
    ResNetSurrogate,
    PINNConfig,
    PhysicsInformedNet,
    NavierStokesPINN,
    EulerPINN,
    DeepONetConfig,
    DeepONet,
    MultiInputDeepONet,
    FNOConfig,
    FNO2d,
    FNO3d,
    TFNO2d,
    UncertaintyConfig,
    EnsembleUQ,
    MCDropoutUQ,
    BayesianUQ,
    TrainingConfig,
    SurrogateTrainer,
    DataAugmentor,
    ActiveLearner,
    evaluate_surrogate,
    train_surrogate,
    cross_validate,
)

# Distributed Computing Module (Phase 13)
from tensornet.distributed import (
    DomainConfig,
    DomainDecomposition,
    SubdomainInfo,
    decompose_domain,
    compute_ghost_zones,
    exchange_ghost_data,
    GPUConfig,
    GPUDevice,
    GPUManager,
    MemoryPool,
    get_available_gpus,
    select_optimal_device,
    distribute_workload,
    CommPattern,
    Communicator,
    AllReduceOp,
    async_send,
    async_recv,
    barrier,
    all_reduce,
    broadcast,
    scatter,
    gather,
    TaskConfig,
    Task,
    TaskGraph,
    DistributedScheduler,
    schedule_dependency_graph,
    execute_parallel,
    ParallelConfig,
    DomainSolver,
    ParallelCGSolver,
    ParallelGMRESSolver,
    SchwarzPreconditioner,
    parallel_solve,
)

# Documentation Module (Phase 14)
from tensornet.docs import (
    ModuleDoc,
    ClassDoc,
    FunctionDoc,
    ParameterDoc,
    APIExtractor,
    extract_module_docs,
    generate_api_markdown,
    generate_api_rst,
    GuideSection,
    Tutorial,
    CodeExample,
    GuideBuilder,
    create_getting_started,
    create_cfd_tutorial,
    create_tensor_network_primer,
    create_deployment_guide,
    SphinxConfig,
    SphinxTheme,
    SphinxBuilder,
    generate_conf_py,
    build_documentation,
    ExampleConfig,
    RunnableExample,
    ExampleRunner,
    validate_example,
    extract_examples_from_docstrings,
)

# Validation Module (Phase 15)
from tensornet.validation import (
    # Physical validation
    ConservationValidator,
    MassConservationTest,
    MomentumConservationTest,
    EnergyConservationTest,
    AnalyticalValidator,
    SodShockValidator,
    BlasiusValidator,
    ObliqueShockValidator,
    IsentropicVortexValidator,
    ValidationResult,
    ValidationSeverity,
    ValidationReport,
    run_physical_validation,
    # Benchmarks
    BenchmarkConfig,
    BenchmarkResult,
    BenchmarkSuite,
    TimerContext,
    PerformanceTimer,
    MemoryTracker,
    MemorySnapshot,
    ScalabilityTest,
    WeakScalingTest,
    StrongScalingTest,
    run_benchmark,
    run_benchmark_suite,
    compare_benchmarks,
    # Regression
    RegressionTest,
    RegressionSuite,
    RegressionResult,
    GoldenValue,
    GoldenValueStore,
    update_golden_values,
    ArrayComparator,
    TensorComparator,
    StateComparator,
    run_regression_tests,
    run_full_regression,
    # V&V
    VVLevel,
    VVCategory,
    VVTest,
    VVTestResult,
    VVPlan,
    VVReport,
    CodeVerification,
    UnitVerification,
    IntegrationVerification,
    ValidationCase,
    ExperimentalValidation,
    AnalyticalValidation,
    UncertaintyBand,
    ValidationUncertainty,
    run_vv_plan,
    generate_vv_report,
)

__all__ = [
    # Core
    "MPS",
    "MPO",
    # Algorithms
    "dmrg",
    "tebd",
    "tebd_step",
    "lanczos_ground_state",
    "tdvp",
    "tdvp_step",
    "imaginary_time_tdvp",
    "TDVPResult",
    # Hamiltonians
    "heisenberg_mpo",
    "tfim_mpo",
    "xx_mpo",
    "xyz_mpo",
    "bose_hubbard_mpo",
    "pauli_matrices",
    "spin_operators",
    # Utilities
    "svd_truncated",
    "qr_positive",
    "ghz_mps",
    "product_mps",
    "random_mps",
    # CFD 1D
    "Euler1D",
    "EulerState",
    "euler_to_mps",
    "mps_to_euler",
    "sod_shock_tube_ic",
    "lax_shock_tube_ic",
    "shu_osher_ic",
    "roe_flux",
    "hll_flux",
    "hllc_flux",
    "exact_riemann",
    "minmod",
    "superbee",
    "van_leer",
    "mc_limiter",
    # CFD 2D
    "Euler2D",
    "Euler2DState",
    "supersonic_wedge_ic",
    "oblique_shock_exact",
    "WedgeGeometry",
    "ImmersedBoundary",
    "BCType",
    "FlowState",
    "BoundaryManager",
    # QTT Compression (Phase 5)
    "field_to_qtt",
    "qtt_to_field",
    "euler_to_qtt",
    "qtt_to_euler",
    "QTTCompressionResult",
    # Deployment (Phase 11)
    "ExportConfig",
    "ExportResult",
    "TensorRTExporter",
    "export_to_onnx",
    "optimize_for_tensorrt",
    "validate_exported_model",
    "benchmark_inference",
    "JetsonConfig",
    "MemoryProfile",
    "PowerMode",
    "EmbeddedRuntime",
    "optimize_memory_layout",
    "configure_jetson_power",
    "create_inference_pipeline",
    # Guidance (Phase 11)
    "AtmosphericModel",
    "VehicleState",
    "AeroCoefficients",
    "TrajectoryConfig",
    "TrajectorySolver",
    "isa_atmosphere",
    "exponential_atmosphere",
    "GuidanceMode",
    "ConstraintType",
    "GuidanceCommand",
    "TrajectoryConstraint",
    "GuidanceController",
    "proportional_navigation",
    "bank_angle_guidance",
    # Simulation (Phase 12)
    "HILConfig",
    "HILMode",
    "SensorModel",
    "IMUSensor",
    "GPSSensor",
    "AirDataSensor",
    "ActuatorModel",
    "ControlSurface",
    "ThrustActuator",
    "HILInterface",
    "create_vehicle_sensors",
    "create_vehicle_actuators",
    "TelemetryFrame",
    "FlightRecord",
    "TrajectoryReconstruction",
    "parse_telemetry",
    "validate_against_flight",
    "AeroTableConfig",
    "AeroTable",
    "RealTimeCFD",
    "build_aero_table",
    "interpolate_coefficients",
    "MissionPhase",
    "MissionConfig",
    "UncertaintyModel",
    "MonteCarloConfig",
    "MissionResult",
    "MissionSimulator",
    "run_monte_carlo",
    "analyze_dispersion",
    # Digital Twin (Phase 13)
    "StateSync",
    "StateSynchronizer",
    "SyncConfig",
    "StateVector",
    "PODModel",
    "DMDModel",
    "AutoencoderROM",
    "ReducedOrderModel",
    "HealthMonitor",
    "StructuralHealth",
    "ThermalHealth",
    "AnomalyDetector",
    "RULEstimator",
    "MaintenanceScheduler",
    "PredictiveMaintenance",
    "DigitalTwin",
    "TwinMode",
    "TwinStatus",
    "create_vehicle_twin",
    "connect_twins",
    "validate_twin_fidelity",
    # ML Surrogates (Phase 13)
    "SurrogateConfig",
    "CFDSurrogate",
    "MLPSurrogate",
    "ResNetSurrogate",
    "PINNConfig",
    "PhysicsInformedNet",
    "NavierStokesPINN",
    "EulerPINN",
    "DeepONetConfig",
    "DeepONet",
    "MultiInputDeepONet",
    "FNOConfig",
    "FNO2d",
    "FNO3d",
    "TFNO2d",
    "UncertaintyConfig",
    "EnsembleUQ",
    "MCDropoutUQ",
    "BayesianUQ",
    "TrainingConfig",
    "SurrogateTrainer",
    "DataAugmentor",
    "ActiveLearner",
    "evaluate_surrogate",
    "train_surrogate",
    "cross_validate",
    # Distributed Computing (Phase 13)
    "DomainConfig",
    "DomainDecomposition",
    "SubdomainInfo",
    "decompose_domain",
    "compute_ghost_zones",
    "exchange_ghost_data",
    "GPUConfig",
    "GPUDevice",
    "GPUManager",
    "MemoryPool",
    "get_available_gpus",
    "select_optimal_device",
    "distribute_workload",
    "CommPattern",
    "Communicator",
    "AllReduceOp",
    "async_send",
    "async_recv",
    "barrier",
    "all_reduce",
    "broadcast",
    "scatter",
    "gather",
    "TaskConfig",
    "Task",
    "TaskGraph",
    "DistributedScheduler",
    "schedule_dependency_graph",
    "execute_parallel",
    "ParallelConfig",
    "DomainSolver",
    "ParallelCGSolver",
    "ParallelGMRESSolver",
    "SchwarzPreconditioner",
    "parallel_solve",
    # Documentation (Phase 14)
    "ModuleDoc",
    "ClassDoc",
    "FunctionDoc",
    "ParameterDoc",
    "APIExtractor",
    "extract_module_docs",
    "generate_api_markdown",
    "generate_api_rst",
    "GuideSection",
    "Tutorial",
    "CodeExample",
    "GuideBuilder",
    "create_getting_started",
    "create_cfd_tutorial",
    "create_tensor_network_primer",
    "create_deployment_guide",
    "SphinxConfig",
    "SphinxTheme",
    "SphinxBuilder",
    "generate_conf_py",
    "build_documentation",
    "ExampleConfig",
    "RunnableExample",
    "ExampleRunner",
    "validate_example",
    "extract_examples_from_docstrings",
    # Validation (Phase 15)
    "ConservationValidator",
    "MassConservationTest",
    "MomentumConservationTest",
    "EnergyConservationTest",
    "AnalyticalValidator",
    "SodShockValidator",
    "BlasiusValidator",
    "ObliqueShockValidator",
    "IsentropicVortexValidator",
    "ValidationResult",
    "ValidationSeverity",
    "ValidationReport",
    "run_physical_validation",
    "BenchmarkConfig",
    "BenchmarkResult",
    "BenchmarkSuite",
    "TimerContext",
    "PerformanceTimer",
    "MemoryTracker",
    "MemorySnapshot",
    "ScalabilityTest",
    "WeakScalingTest",
    "StrongScalingTest",
    "run_benchmark",
    "run_benchmark_suite",
    "compare_benchmarks",
    "RegressionTest",
    "RegressionSuite",
    "RegressionResult",
    "GoldenValue",
    "GoldenValueStore",
    "update_golden_values",
    "ArrayComparator",
    "TensorComparator",
    "StateComparator",
    "run_regression_tests",
    "run_full_regression",
    "VVLevel",
    "VVCategory",
    "VVTest",
    "VVTestResult",
    "VVPlan",
    "VVReport",
    "CodeVerification",
    "UnitVerification",
    "IntegrationVerification",
    "ValidationCase",
    "ExperimentalValidation",
    "AnalyticalValidation",
    "UncertaintyBand",
    "ValidationUncertainty",
    "run_vv_plan",
    "generate_vv_report",
]
