"""
Clifford Algebra and Multivector Implementation

Core data structures for geometric algebra:
- CliffordAlgebra: Defines the algebra structure (signature, metric)
- Multivector: Elements of the algebra with 2^n components
- Factory functions for creating special multivectors

Copyright (c) 2026 Tigantic Holdings LLC. All Rights Reserved.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple, Iterable
import torch
from functools import lru_cache
import itertools


@dataclass(frozen=True)
class CliffordAlgebra:
    """
    Defines a Clifford algebra Cl(p, q, r).
    
    The algebra is generated by n = p + q + r orthonormal basis vectors:
    - p vectors square to +1
    - q vectors square to -1
    - r vectors square to 0 (degenerate)
    
    The algebra has dimension 2^n with basis blades indexed by
    subsets of {0, 1, ..., n-1}.
    
    Attributes:
        p: Number of positive signature generators
        q: Number of negative signature generators
        r: Number of degenerate generators
    """
    p: int
    q: int = 0
    r: int = 0
    
    def __post_init__(self):
        if self.p < 0 or self.q < 0 or self.r < 0:
            raise ValueError("Signature components must be non-negative")
    
    @property
    def n(self) -> int:
        """Total number of generators."""
        return self.p + self.q + self.r
    
    @property
    def dim(self) -> int:
        """Dimension of the algebra (number of basis blades)."""
        return 2 ** self.n
    
    @property
    def metric(self) -> torch.Tensor:
        """
        Diagonal metric tensor.
        
        Returns tensor [+1, ..., +1, -1, ..., -1, 0, ..., 0]
        with p ones, q negative ones, r zeros.
        """
        diag = torch.ones(self.n)
        diag[self.p:self.p + self.q] = -1
        diag[self.p + self.q:] = 0
        return diag
    
    def basis_vector_square(self, i: int) -> float:
        """Return e_i^2 according to the metric."""
        if i < self.p:
            return 1.0
        elif i < self.p + self.q:
            return -1.0
        else:
            return 0.0
    
    @lru_cache(maxsize=None)
    def blade_grade(self, blade_index: int) -> int:
        """
        Grade (number of 1 bits) of a blade index.
        
        Blade index k represents the blade with basis vectors
        at positions where bit i is set.
        """
        return bin(blade_index).count('1')
    
    @lru_cache(maxsize=None)
    def grade_indices(self, grade: int) -> Tuple[int, ...]:
        """Return all blade indices of a given grade."""
        return tuple(
            k for k in range(self.dim)
            if self.blade_grade(k) == grade
        )
    
    @lru_cache(maxsize=None)
    def sign_and_result(self, a: int, b: int) -> Tuple[int, int]:
        """
        Compute sign and result of geometric product of basis blades.
        
        For basis blades represented by bit patterns a and b,
        compute the sign and resulting blade index.
        
        Args:
            a: Blade index (bit pattern)
            b: Blade index (bit pattern)
            
        Returns:
            (sign, result_blade_index)
            sign is +1, -1, or 0
        """
        # Track sign from permutations and metric
        sign = 1
        result = a ^ b  # XOR gives basis vectors appearing odd times
        common = a & b  # Common vectors (will square)
        
        # Count swaps needed to bring matching vectors together
        # For each bit in b, count bits to its right in a
        temp_a = a
        temp_b = b
        for i in range(self.n):
            if (temp_b >> i) & 1:
                # Count bits in a to the right of position i that are in a
                # Actually, count bits in a that are above position i
                bits_above = bin(temp_a >> (i + 1)).count('1')
                if bits_above % 2 == 1:
                    sign *= -1
        
        # Handle metric from squared terms
        for i in range(self.n):
            if (common >> i) & 1:
                metric_val = self.basis_vector_square(i)
                if metric_val == 0:
                    return 0, 0
                sign *= int(metric_val)
        
        return sign, result
    
    def blade_to_indices(self, blade_index: int) -> List[int]:
        """Convert blade index to list of generator indices."""
        return [i for i in range(self.n) if (blade_index >> i) & 1]
    
    def indices_to_blade(self, indices: Iterable[int]) -> int:
        """Convert generator indices to blade index."""
        blade = 0
        for i in indices:
            blade |= (1 << i)
        return blade
    
    def blade_str(self, blade_index: int) -> str:
        """String representation of a basis blade."""
        if blade_index == 0:
            return "1"
        indices = self.blade_to_indices(blade_index)
        return "e" + "".join(str(i + 1) for i in indices)
    
    def __repr__(self) -> str:
        return f"Cl({self.p},{self.q},{self.r})"


@dataclass
class Multivector:
    """
    Element of a Clifford algebra.
    
    Represented as a dense tensor of 2^n coefficients.
    
    Attributes:
        algebra: The Clifford algebra
        coeffs: Tensor of shape (2^n,) with coefficients
    """
    algebra: CliffordAlgebra
    coeffs: torch.Tensor
    
    def __post_init__(self):
        if self.coeffs.shape[-1] != self.algebra.dim:
            raise ValueError(
                f"Coefficients have wrong dimension: "
                f"expected {self.algebra.dim}, got {self.coeffs.shape[-1]}"
            )
    
    @classmethod
    def zero(cls, algebra: CliffordAlgebra, 
             dtype: torch.dtype = torch.float64) -> Multivector:
        """Create zero multivector."""
        return cls(algebra, torch.zeros(algebra.dim, dtype=dtype))
    
    @classmethod
    def scalar(cls, algebra: CliffordAlgebra, value: float) -> Multivector:
        """Create scalar multivector."""
        coeffs = torch.zeros(algebra.dim, dtype=torch.float64)
        coeffs[0] = value
        return cls(algebra, coeffs)
    
    @classmethod
    def basis_blade(cls, algebra: CliffordAlgebra, blade_index: int,
                    coefficient: float = 1.0) -> Multivector:
        """Create a single basis blade."""
        coeffs = torch.zeros(algebra.dim, dtype=torch.float64)
        coeffs[blade_index] = coefficient
        return cls(algebra, coeffs)
    
    @classmethod
    def basis_vector(cls, algebra: CliffordAlgebra, 
                     index: int, coefficient: float = 1.0) -> Multivector:
        """Create a single basis vector e_i."""
        blade_index = 1 << index
        return cls.basis_blade(algebra, blade_index, coefficient)
    
    @classmethod
    def from_vector(cls, algebra: CliffordAlgebra, 
                    components: List[float]) -> Multivector:
        """Create a vector (grade-1 multivector)."""
        if len(components) != algebra.n:
            raise ValueError(f"Expected {algebra.n} components")
        coeffs = torch.zeros(algebra.dim, dtype=torch.float64)
        for i, c in enumerate(components):
            coeffs[1 << i] = c
        return cls(algebra, coeffs)
    
    @classmethod
    def from_bivector_dict(cls, algebra: CliffordAlgebra,
                           components: Dict[Tuple[int, int], float]) -> Multivector:
        """
        Create bivector from dictionary of {(i, j): coefficient}.
        
        Indices are 0-based generator indices.
        """
        coeffs = torch.zeros(algebra.dim, dtype=torch.float64)
        for (i, j), c in components.items():
            if i >= j:
                raise ValueError(f"Indices must be ordered: ({i}, {j})")
            blade = (1 << i) | (1 << j)
            coeffs[blade] = c
        return cls(algebra, coeffs)
    
    @property
    def grades(self) -> List[int]:
        """List of non-zero grades in this multivector."""
        nonzero_grades = set()
        for k in range(self.algebra.dim):
            if abs(self.coeffs[k]) > 1e-14:
                nonzero_grades.add(self.algebra.blade_grade(k))
        return sorted(nonzero_grades)
    
    def grade_projection(self, grade: int) -> Multivector:
        """Project to a single grade."""
        new_coeffs = torch.zeros_like(self.coeffs)
        for k in self.algebra.grade_indices(grade):
            new_coeffs[k] = self.coeffs[k]
        return Multivector(self.algebra, new_coeffs)
    
    def scalar_part(self) -> float:
        """Extract scalar component."""
        return float(self.coeffs[0])
    
    def vector_part(self) -> torch.Tensor:
        """Extract vector components."""
        indices = self.algebra.grade_indices(1)
        return self.coeffs[list(indices)]
    
    def bivector_part(self) -> torch.Tensor:
        """Extract bivector components."""
        indices = self.algebra.grade_indices(2)
        return self.coeffs[list(indices)]
    
    @property
    def is_scalar(self) -> bool:
        """True if only scalar component is non-zero."""
        return self.grades == [0] or len(self.grades) == 0
    
    @property  
    def is_vector(self) -> bool:
        """True if only grade-1 components are non-zero."""
        return self.grades == [1]
    
    @property
    def is_bivector(self) -> bool:
        """True if only grade-2 components are non-zero."""
        return self.grades == [2]
    
    @property
    def is_even(self) -> bool:
        """True if only even-grade components are non-zero."""
        return all(g % 2 == 0 for g in self.grades)
    
    @property
    def is_odd(self) -> bool:
        """True if only odd-grade components are non-zero."""
        return all(g % 2 == 1 for g in self.grades)
    
    def __add__(self, other: Multivector) -> Multivector:
        if self.algebra != other.algebra:
            raise ValueError("Cannot add multivectors from different algebras")
        return Multivector(self.algebra, self.coeffs + other.coeffs)
    
    def __sub__(self, other: Multivector) -> Multivector:
        if self.algebra != other.algebra:
            raise ValueError("Cannot subtract multivectors from different algebras")
        return Multivector(self.algebra, self.coeffs - other.coeffs)
    
    def __neg__(self) -> Multivector:
        return Multivector(self.algebra, -self.coeffs)
    
    def __mul__(self, scalar: float) -> Multivector:
        return Multivector(self.algebra, self.coeffs * scalar)
    
    def __rmul__(self, scalar: float) -> Multivector:
        return self.__mul__(scalar)
    
    def __truediv__(self, scalar: float) -> Multivector:
        return Multivector(self.algebra, self.coeffs / scalar)
    
    def __eq__(self, other: Multivector) -> bool:
        if self.algebra != other.algebra:
            return False
        return torch.allclose(self.coeffs, other.coeffs, atol=1e-12)
    
    def norm_squared(self) -> float:
        """Squared Euclidean norm of coefficient vector."""
        return float((self.coeffs ** 2).sum())
    
    def norm(self) -> float:
        """Euclidean norm of coefficient vector."""
        return float(torch.sqrt((self.coeffs ** 2).sum()))
    
    def __repr__(self) -> str:
        terms = []
        for k in range(self.algebra.dim):
            c = float(self.coeffs[k])
            if abs(c) > 1e-14:
                blade_str = self.algebra.blade_str(k)
                if len(terms) == 0:
                    terms.append(f"{c:.4f}*{blade_str}")
                elif c > 0:
                    terms.append(f" + {c:.4f}*{blade_str}")
                else:
                    terms.append(f" - {-c:.4f}*{blade_str}")
        if not terms:
            return "0"
        return "".join(terms)


# Factory functions
def scalar(algebra: CliffordAlgebra, value: float) -> Multivector:
    """Create scalar multivector."""
    return Multivector.scalar(algebra, value)


def vector(algebra: CliffordAlgebra, components: List[float]) -> Multivector:
    """Create vector (grade-1) multivector."""
    return Multivector.from_vector(algebra, components)


def bivector(algebra: CliffordAlgebra, 
             components: Dict[Tuple[int, int], float]) -> Multivector:
    """Create bivector from {(i,j): coefficient} dict."""
    return Multivector.from_bivector_dict(algebra, components)


def pseudoscalar(algebra: CliffordAlgebra, coefficient: float = 1.0) -> Multivector:
    """Create the pseudoscalar (highest grade blade)."""
    blade_index = (1 << algebra.n) - 1  # All bits set
    return Multivector.basis_blade(algebra, blade_index, coefficient)


def random_multivector(algebra: CliffordAlgebra,
                       grades: Optional[List[int]] = None) -> Multivector:
    """Create random multivector, optionally restricted to certain grades."""
    coeffs = torch.zeros(algebra.dim, dtype=torch.float64)
    
    if grades is None:
        coeffs = torch.randn(algebra.dim, dtype=torch.float64)
    else:
        for grade in grades:
            for k in algebra.grade_indices(grade):
                coeffs[k] = torch.randn(1).item()
    
    return Multivector(algebra, coeffs)
