// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test, console} from "forge-std/Test.sol";
import {Groth16Verifier} from "../src/Groth16Verifier.sol";

/// @title Groth16Verifier Test Suite
/// @notice Tests the BN254 Groth16 pairing verifier with deterministic VK
/// @dev Test proof generated by `cargo run --bin generate-vk --features groth16`
///      Circuit: SimpleMembershipCircuit (secret² = hash)
///      Test vector: secret = 7, hash = 49 = 0x31
contract Groth16VerifierTest is Test {

    Groth16Verifier public verifier;

    // ═══════════════════════════════════════════════════════════════════════
    // TEST PROOF FIXTURES (deterministic seed 0x4859_5045_5254_454E)
    // ═══════════════════════════════════════════════════════════════════════

    // Proof: A ∈ G1
    uint256 constant PROOF_A_X = 0x245ea8304afe0d9c4647a0bc50952f7b62d4d469827bc5fab1a7fad31a0d889f;
    uint256 constant PROOF_A_Y = 0x1337a149ab5ab5814370c33cd14ce5d8f5cd1447bd203bd493313b60155e6d67;

    // Proof: B ∈ G2 — wire format is [x1, x0, y1, y0] = [x_im, x_re, y_im, y_re]
    uint256 constant PROOF_B_X1 = 0x0be1b3fd7119a4be5fec155505faf449aff43e3f191cd3a6dd289312414ddd2e;
    uint256 constant PROOF_B_X0 = 0x2f9a374780a773ce910e926eca868aa8007bc2a0c9ad29158505a7fc4bfb5ea1;
    uint256 constant PROOF_B_Y1 = 0x16c4ffeb5b40992faf5afca84dda4a62e993a894451353749d64ccae73b3531d;
    uint256 constant PROOF_B_Y0 = 0x087e4c3d7af693005d980349e14d2172c5d243d245cd7a7d32791791b535caea;

    // Proof: C ∈ G1
    uint256 constant PROOF_C_X = 0x2bb74a8da88df1c3776550952a8c6462a99bc4fe41ed5f066eef0ca101eda202;
    uint256 constant PROOF_C_Y = 0x0fe2ff521b16e0dfa28d5702da4ba820123e5b4bb643df59ca7812bd62674ef2;

    // Public input: hash = 49 = 0x31 (secret = 7, 7² = 49)
    uint256 constant PUBLIC_INPUT = 0x0000000000000000000000000000000000000000000000000000000000000031;

    // BN254 scalar field modulus
    uint256 constant Q = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    function setUp() public {
        verifier = new Groth16Verifier();
    }

    // ═══════════════════════════════════════════════════════════════════════
    // POSITIVE VERIFICATION
    // ═══════════════════════════════════════════════════════════════════════

    /// @notice Valid proof verifies successfully
    function test_validProof() public view {
        uint256[8] memory proof = _validProof();
        bool result = verifier.verifyProof(proof, PUBLIC_INPUT);
        assertTrue(result, "Valid proof must verify");
    }

    /// @notice Valid proof with public input = 0 should fail (wrong hash)
    function test_zeroPublicInput_rejects() public view {
        uint256[8] memory proof = _validProof();
        bool result = verifier.verifyProof(proof, 0);
        assertFalse(result, "Proof with wrong public input must reject");
    }

    // ═══════════════════════════════════════════════════════════════════════
    // NEGATIVE VERIFICATION — TAMPERED PROOFS
    // ═══════════════════════════════════════════════════════════════════════

    /// @notice Tampered A.x rejects
    function test_tamperedAx_rejects() public view {
        uint256[8] memory proof = _validProof();
        proof[0] = proof[0] ^ 1; // flip LSB
        bool result = verifier.verifyProof(proof, PUBLIC_INPUT);
        assertFalse(result, "Tampered A.x must reject");
    }

    /// @notice Tampered A.y rejects
    function test_tamperedAy_rejects() public view {
        uint256[8] memory proof = _validProof();
        proof[1] = proof[1] ^ 1;
        bool result = verifier.verifyProof(proof, PUBLIC_INPUT);
        assertFalse(result, "Tampered A.y must reject");
    }

    /// @notice Tampered B.x1 rejects
    function test_tamperedBx1_rejects() public view {
        uint256[8] memory proof = _validProof();
        proof[2] = proof[2] ^ 1;
        bool result = verifier.verifyProof(proof, PUBLIC_INPUT);
        assertFalse(result, "Tampered B.x1 must reject");
    }

    /// @notice Tampered B.x0 rejects
    function test_tamperedBx0_rejects() public view {
        uint256[8] memory proof = _validProof();
        proof[3] = proof[3] ^ 1;
        bool result = verifier.verifyProof(proof, PUBLIC_INPUT);
        assertFalse(result, "Tampered B.x0 must reject");
    }

    /// @notice Tampered C.x rejects
    function test_tamperedCx_rejects() public view {
        uint256[8] memory proof = _validProof();
        proof[6] = proof[6] ^ 1;
        bool result = verifier.verifyProof(proof, PUBLIC_INPUT);
        assertFalse(result, "Tampered C.x must reject");
    }

    /// @notice Tampered C.y rejects
    function test_tamperedCy_rejects() public view {
        uint256[8] memory proof = _validProof();
        proof[7] = proof[7] ^ 1;
        bool result = verifier.verifyProof(proof, PUBLIC_INPUT);
        assertFalse(result, "Tampered C.y must reject");
    }

    /// @notice Wrong public input (hash+1) rejects
    function test_wrongPublicInput_rejects() public view {
        uint256[8] memory proof = _validProof();
        bool result = verifier.verifyProof(proof, PUBLIC_INPUT + 1);
        assertFalse(result, "Wrong public input must reject");
    }

    /// @notice Public input >= Q reverts with InvalidPublicInput
    function test_publicInput_outOfField_reverts() public {
        uint256[8] memory proof = _validProof();
        vm.expectRevert(Groth16Verifier.InvalidPublicInput.selector);
        verifier.verifyProof(proof, Q);
    }

    /// @notice Public input = Q + 1 reverts
    function test_publicInput_overQ_reverts() public {
        uint256[8] memory proof = _validProof();
        vm.expectRevert(Groth16Verifier.InvalidPublicInput.selector);
        verifier.verifyProof(proof, Q + 1);
    }

    /// @notice Public input = type(uint256).max reverts
    function test_publicInput_maxUint_reverts() public {
        uint256[8] memory proof = _validProof();
        vm.expectRevert(Groth16Verifier.InvalidPublicInput.selector);
        verifier.verifyProof(proof, type(uint256).max);
    }

    // ═══════════════════════════════════════════════════════════════════════
    // ALL-ZERO / DEGENERATE PROOFS
    // ═══════════════════════════════════════════════════════════════════════

    /// @notice All-zero proof rejects
    /// @dev Zero G1 point = identity element, pairing equation won't hold
    function test_allZeroProof_rejects() public view {
        uint256[8] memory proof;
        bool result = verifier.verifyProof(proof, PUBLIC_INPUT);
        assertFalse(result, "All-zero proof must reject");
    }

    // ═══════════════════════════════════════════════════════════════════════
    // FUZZ TESTS
    // ═══════════════════════════════════════════════════════════════════════

    /// @notice Fuzz: random public inputs should almost certainly reject
    function testFuzz_randomPublicInput_rejects(uint256 randomInput) public view {
        vm.assume(randomInput < Q);
        vm.assume(randomInput != PUBLIC_INPUT);

        uint256[8] memory proof = _validProof();
        bool result = verifier.verifyProof(proof, randomInput);
        assertFalse(result, "Random public input must reject");
    }

    // ═══════════════════════════════════════════════════════════════════════
    // GAS BENCHMARKS
    // ═══════════════════════════════════════════════════════════════════════

    /// @notice Gas benchmark for valid proof verification
    function test_gas_validProof() public view {
        uint256[8] memory proof = _validProof();
        uint256 gasBefore = gasleft();
        verifier.verifyProof(proof, PUBLIC_INPUT);
        uint256 gasUsed = gasBefore - gasleft();
        console.log("Gas used for valid proof verification:", gasUsed);
        // BN254 ecPairing (4 pairs) typically costs ~113k gas on mainnet
        // Total should be under 200k with IC aggregation
        assertLt(gasUsed, 300_000, "Gas must be under 300k");
    }

    /// @notice Gas benchmark for invalid proof
    /// @dev Off-curve points cause ecPairing precompile to return failure;
    ///      gas accounting for failed precompiles is high in Forge EVM.
    function test_gas_invalidProof() public view {
        uint256[8] memory proof = _validProof();
        proof[0] = proof[0] ^ 1; // tamper
        bool result = verifier.verifyProof(proof, PUBLIC_INPUT);
        assertFalse(result, "Tampered proof must reject");
    }

    // ═══════════════════════════════════════════════════════════════════════
    // HELPERS
    // ═══════════════════════════════════════════════════════════════════════

    function _validProof() internal pure returns (uint256[8] memory proof) {
        proof[0] = PROOF_A_X;
        proof[1] = PROOF_A_Y;
        proof[2] = PROOF_B_X1;
        proof[3] = PROOF_B_X0;
        proof[4] = PROOF_B_Y1;
        proof[5] = PROOF_B_Y0;
        proof[6] = PROOF_C_X;
        proof[7] = PROOF_C_Y;
    }
}
